### PR TITLE
fix mixer toggle button bug

### LINKED ISSUE #549: StakeShuffle Page bug.
On the StakeShuffle page, when the start mixer toggle is clicked, the toggle becomes active... However, if you exit and return to the StakeShuffle page, the toggles goes back to an inactive state while mixer is still running.
For some reason, the toggle state is not saved.
Screenshot 2021-08-03 at 07 56 40

Screenshot 2021-08-03 at 07 58 55

Lastly, at the danger zone section, if the allow spending from unmixed account is toggled and the page is exited, the toggle state returns to an inactive state. 
This is an issue because the user would not know if this is active or not.

### PR DESCRIPTION
**Pull request by Sirmorrison**
Close #549 

* Set the mixer toggle to active when mixer is running.
* Disabled spend from unmixed account toggle as it is not yet implemented.

### CODE REVIEW

File: ui/page/privacy_page.go [hunk 1]
```diff
@@ -436,4 +436,8 @@ func (pg *PrivacyPage) showModalPasswordStartAccountMixer() {
 		}).Show()
 }
 
+func (pg *PrivacyPage) updateMixerOptions() {
+	pg.toggleMixer.SetChecked(pg.wallet.IsAccountMixerActive())
```
Comment (oshorefueled) [inline ui/page/privacy_page.go]: does this need to be wrapped in a method?

File: ui/page/privacy_page.go [hunk 2]
```diff
@@ -54,6 +53,7 @@ func (pg *PrivacyPage) OnResume() {
 }
 
 func (pg *PrivacyPage) Layout(gtx layout.Context) layout.Dimensions {
+	pg.updateMixerOptions()
```
Comment (oshorefueled) [inline ui/page/privacy_page.go]: This should be in the OnResume method

File: ui/page/privacy_page.go [hunk 3]
```diff
@@ -17,35 +14,37 @@ import (
...
-		allowUnspendUnmixedAcct: new(widget.Bool),
+		toggleMixer:             l.Theme.Switch(),
+		allowUnspendUnmixedAcct: l.Theme.Switch(),
 		toPrivacySetup:          l.Theme.Button(new(widget.Clickable), "Set up mixer for this wallet"),
 		dangerZoneCollapsible:   l.Theme.Collapsible(),
 	}
 	pg.toPrivacySetup.Background = l.Theme.Color.Primary
 	pg.backButton, pg.infoButton = components.SubpageHeaderButtons(l)
-
+	pg.allowUnspendUnmixedAcct.Disabled()
```
Comment (oshorefueled) [inline ui/page/privacy_page.go]: This would probably be in the OnResume method

**Review by oshorefueled — CHANGES_REQUESTED** [review]

**Review by beansgum — APPROVED** [review]

**Review by oshorefueled — APPROVED** [review]
