### PR TITLE
fix app crash after wallet restore is complete

### LINKED ISSUE #1034: nil pointer dereference with wallet hex restore
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x124d53a]

goroutine 106517 [running]:
github.com/planetdecred/godcr/ui/page/components.(*WalletSelector).UnlockWalletForSyncing(0xc0038c2000, 0xc005ac21e0)
        /home/user/code/godcr/ui/page/components/wallet_selector.go:474 +0x1fa
github.com/planetdecred/godcr/ui/page/components.(*WalletSelector).startSyncing(0xc0038c2000)
        /home/user/code/godcr/ui/page/components/wallet_selector.go:439 +0x89
github.com/planetdecred/godcr/ui/page/components.(*WalletSelector).Expose(0xc0038c2000, {0x1ddf078?, 0xc003a68b00?})
        /home/user/code/godcr/ui/page/components/wallet_selector.go:70 +0xd7
github.com/planetdecred/godcr/ui/page.(*WalletDexServerSelector).OnNavigatedTo(0xc005e54180)
        /home/user/code/godcr/ui/page/wallet_dex_selector_page.go:72 +0x6d
github.com/planetdecred/godcr/app.(*PageStack).Reset(0xc001f766c0, {0xc005dd0240, 0x1, 0x1})
        /home/user/code/godcr/app/pagestack.go:153 +0x112
github.com/planetdecred/godcr/app.(*SimpleWindowNavigator).ClearStackAndDisplay(0xc001f766f0, {0x1de32e8, 0xc005e54180})
        /home/user/code/godcr/app/window.go:84 +0x8f
github.com/planetdecred/godcr/ui/page.(*CreateWallet).handlerWalletDexServerSelectorCallBacks(0xc00215b100)
        /home/user/code/godcr/ui/page/wallet_setup_page.go:492 +0x9f
github.com/planetdecred/godcr/ui/page.(*CreateWallet).HandleUserInteractions.func3()
        /home/user/code/godcr/ui/page/wallet_setup_page.go:451 +0x1d
github.com/planetdecred/godcr/ui/page/info.(*Restore).showHexRestoreModal.func1.1.2.1()
        /home/user/code/godcr/ui/page/info/restore_page.go:256 +0x12d
created by github.com/planetdecred/godcr/ui/page/info.(*Restore).showHexRestoreModal.func1.1.2
        /home/user/code/godcr/ui/page/info/restore_page.go:243 +0x125

### PR DESCRIPTION
**Pull request by Sirmorrison**
Fix #1034 

This pr fixes the app crash bug after a wallet is restored.

### CODE REVIEW

File: ui/page/wallet_dex_selector_page.go [hunk 1]
```diff
@@ -223,3 +229,44 @@ func (pg *WalletDexServerSelector) layoutAddMoreRowSection(clk *decredmaterial.C
...
+	for _, wal := range pg.WL.SortedWalletList() {
+		if !wal.HasDiscoveredAccounts && wal.IsLocked() {
+			pg.UnlockWalletForSyncing(wal)
+			return
+		}
+	}
+
+	err := pg.WL.MultiWallet.SpvSync()
+	if err != nil {
+		// show error dialog
```
Comment (dreacot) [inline ui/page/wallet_dex_selector_page.go:243]: no error dialog seems to be shown here

**Review by dreacot — APPROVED** [review]
Looks good to go!

**Review by JustinBeBoy — APPROVED** [review]
