### PR TITLE
fix crash that occurs when navigating to the consensus page

### LINKED ISSUE #883: Crash when fetching agendas on mainnet
Segfault when fetching mainnet agendas. [Logs](https://bpa.st/3IPQ)

### PR DESCRIPTION
**Pull request by dreacot**
Requires https://github.com/planetdecred/dcrlibwallet/pull/243
Resolves #883

The crash was caused because an agenda type which wasn't accounted for was provided from the API, and there wasn't any assets(icons, colors, etc) provided for the rogue status type, which led to a nil pointer exception.

The fix was to check for all possible agenda status types, and provide assets for them to render to the UI

### CODE REVIEW

File: ui/page/components/consensus_list.go [hunk 1]
```diff
@@ -41,25 +41,43 @@ func layoutAgendaStatus(gtx C, l *load.Load, agenda dcrlibwallet.Agenda) D {
...
+		statusLabel = l.Theme.Label(values.MarginPadding14, agenda.Status)
+		statusLabel.Color = l.Theme.Color.GreenText
+		statusIcon = decredmaterial.NewIcon(l.Icons.NavigationCheck)
+		statusIcon.Color = l.Theme.Color.Green500
+		backgroundColor = l.Theme.Color.Green50
+	case dcrlibwallet.AgendaStatusFailed.String():
+		statusLabel = l.Theme.Label(values.MarginPadding14, agenda.Status)
+		statusLabel.Color = l.Theme.Color.Text
+		statusIcon = decredmaterial.NewIcon(l.Icons.NavigationCancel)
+		statusIcon.Color = l.Theme.Color.GrayText1
```
Comment (Sirmorrison) [inline ui/page/components/consensus_list.go]:
```suggestion
		statusIcon.Color = l.Theme.Color.Gray1
```

File: ui/page/components/consensus_list.go [hunk 2]
```diff
@@ -41,25 +41,43 @@ func layoutAgendaStatus(gtx C, l *load.Load, agenda dcrlibwallet.Agenda) D {
...
 		statusLabel = l.Theme.Label(values.MarginPadding14, agenda.Status)
 		statusLabel.Color = l.Theme.Color.Text
 		statusIcon = decredmaterial.NewIcon(l.Icons.PlayIcon)
 		statusIcon.Color = l.Theme.Color.DeepBlue
 		backgroundColor = l.Theme.Color.Gray2
+	default:
+		statusLabel = l.Theme.Label(values.MarginPadding14, agenda.Status)
+		statusLabel.Color = l.Theme.Color.Text
+		statusIcon = decredmaterial.NewIcon(l.Icons.NavMoreIcon)
+		statusIcon.Color = l.Theme.Color.GrayText1
```
Comment (Sirmorrison) [inline ui/page/components/consensus_list.go]:
```suggestion
		statusIcon.Color = l.Theme.Color.Gray1
```

**Review by Sirmorrison — CHANGES_REQUESTED** [review]

**Review by Sirmorrison — APPROVED** [review]
