### PR TITLE
Sign message bug

### LINKED ISSUE #543: Sign message button bug
When the sign message page is opened without moving the mouse, the `sign message` button is shown as active. However, when the mouse is moved, the page colors tend to update.

Also, when the sign message button is clicked with all inputs empty, there is a flashing error that does not stay. see screen shots below.
ezgif com-gif-maker(4)

Also, when there is an error from the address editor, the sign message button is active, which should not be so.
image

### PR DESCRIPTION
**Pull request by Sirmorrison**
Close #543 

This pr resolve issue with 
* fix active sign message button color when page is opened
* fix active sign message button color when error exist
* fix issue with flashing error message

### CODE REVIEW

File: ui/page/sign_message_page.go [hunk 1]
```diff
@@ -252,54 +271,69 @@ func (pg *SignMessagePage) Handle() {
...
+	pg.messageEditor.SetError("")
 	pg.signedMessageLabel.Text = ""
 	pg.errorLabel.Text = ""
+	pg.isValidatedMsg = false
+	pg.isValidatedAddress = false
 }
 
-func (pg *SignMessagePage) OnClose() {}
+func (pg *SignMessagePage) OnClose() {
+	pg.clearForm()
```
Comment (beansgum) [inline ui/page/sign_message_page.go]: This isn't required since the page isn't data persisted when closed.

File: ui/page/sign_message_page.go [hunk 2]
```diff
@@ -20,11 +21,12 @@ const SignMessagePageID = "SignMessage"
 
 type SignMessagePage struct {
 	*load.Load
-	theme     *decredmaterial.Theme
 	container layout.List
 	wallet    *dcrlibwallet.Wallet
 
 	isSigningMessage                           bool
+	isValidatedMsg                             bool
+	isValidatedAddress                         bool
```
Comment (beansgum) [inline ui/page/sign_message_page.go]: Proper name should be `hasValidatedMsg` or `addressIsValid`

File: ui/page/sign_message_page.go [hunk 3]
```diff
@@ -252,54 +271,69 @@ func (pg *SignMessagePage) Handle() {
 	}
 }
 
-func (pg *SignMessagePage) validate(ignoreEmpty bool) bool {
-	isAddressValid := pg.validateAddress(ignoreEmpty)
-	isMessageValid := pg.validateMessage(ignoreEmpty)
+func (pg *SignMessagePage) validate() bool {
+	isAddressValid := pg.validateAddress()
+	isMessageValid := pg.validateMessage()
```
Comment (beansgum) [inline ui/page/sign_message_page.go]:
```suggestion
	addressIsValid := pg.validateAddress()
	messageIsValid := pg.validateMessage()
```

File: ui/page/sign_message_page.go (hunk 2 above)
Comment (beansgum) [reply ui/page/sign_message_page.go]: These two variables are modified in several references but only used once and they were used together. Instead of two variables, make it one and it should be `true` if message and address is valid.

**Review by beansgum — CHANGES_REQUESTED** [review]

**Review by beansgum — APPROVED** [review]

**Review by oshorefueled — APPROVED** [review]
