### PR TITLE
fix crash on send page

### LINKED ISSUE #358: crash after creating new accounts and navigating to the send page.
After creating new accounts and going to the send page, godcr crashes with the terminal log below. 

account-selection-bug

panic: runtime error: index out of range [4] with length 4

goroutine 52 [running]:
github.com/planetdecred/godcr/ui.(*sendPage).walletAccountSection.func2.1.1.1.1.1(0x0, 0x0, 0x18a, 0xf4240, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, 0x5a13ae0, ...)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/send_page.go:686 +0x1253
gioui.org/layout.(*List).Layout(0xc0009925b0, 0x0, 0x0, 0x18a, 0xf4240, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, ...)
        /Users/klinsmann/go/pkg/mod/gioui.org@v0.0.0-20210228180843-e1248651c871/layout/list.go:111 +0x165
github.com/planetdecred/godcr/ui.(*sendPage).walletAccountSection.func2.1.1.1.1(0x0, 0x0, 0x18a, 0xf4215, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, 0x5a13ae0, ...)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/send_page.go:667 +0x127
gioui.org/layout.Flex.Layout(0x4000001, 0x0, 0x0, 0x18a, 0xf4236, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, ...)
        /Users/klinsmann/go/pkg/mod/gioui.org@v0.0.0-20210228180843-e1248651c871/layout/flex.go:99 +0xd86
github.com/planetdecred/godcr/ui.(*sendPage).popupSections(0xc000992000, 0x0, 0x0, 0x18a, 0xf4236, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, ...)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/send_page.go:1061 +0x25b
github.com/planetdecred/godcr/ui.(*sendPage).walletAccountSection.func2.1.1.1(0x0, 0x0, 0x18a, 0xf4236, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, 0x5a13ae0, ...)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/send_page.go:666 +0x1a4
gioui.org/layout.Inset.Layout(0x0, 0x0, 0x141200000, 0x0, 0x0, 0x0, 0x18a, 0xf4236, 0x3f8000003f800000, 0x5071440, ...)
        /Users/klinsmann/go/pkg/mod/gioui.org@v0.0.0-20210228180843-e1248651c871/layout/layout.go:147 +0x4e5
github.com/planetdecred/godcr/ui.(*sendPage).walletAccountSection.func2.1.1(0x0, 0x0, 0x18a, 0xf4240, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, 0x5a13ae0, ...)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/send_page.go:665 +0x2a6
gioui.org/layout.(*List).Layout(0xc0009922d8, 0x0, 0x0, 0x18a, 0xf4240, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, ...)
        /Users/klinsmann/go/pkg/mod/gioui.org@v0.0.0-20210228180843-e1248651c871/layout/list.go:111 +0x165
github.com/planetdecred/godcr/ui.(*sendPage).walletAccountSection.func2.1(0x0, 0x0, 0x18a, 0xf422c, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, 0x5a13ae0, ...)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/send_page.go:653 +0xe6
gioui.org/layout.Stack.Layout(0x4bead00, 0x18a, 0x0, 0x18a, 0xf422c, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, ...)
        /Users/klinsmann/go/pkg/mod/gioui.org@v0.0.0-20210228180843-e1248651c871/layout/stack.go:78 +0x6d7
github.com/planetdecred/godcr/ui.(*sendPage).walletAccountSection.func2(0x18a, 0x0, 0x18a, 0xf422c, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, 0x5a13ae0, ...)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/send_page.go:651 +0x2d1
gioui.org/layout.Inset.Layout(0x141200000, 0x141200000, 0x141200000, 0x141200000, 0x18a, 0x0, 0x18a, 0xf422c, 0x3f8000003f800000, 0x5071440, ...)
        /Users/klinsmann/go/pkg/mod/gioui.org@v0.0.0-20210228180843-e1248651c871/layout/layout.go:147 +0x4e5
github.com/planetdecred/godcr/ui/decredmaterial.(*Modal).Layout.func2.1.1.1.1.1(0x19e, 0x0, 0x19e, 0xf4240, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, 0x5a13ae0, ...)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/decredmaterial/modal.go:55 +0xc6
gioui.org/layout.(*List).Layout(0xc00098c600, 0x0, 0x0, 0x19e, 0xf4240, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, ...)
        /Users/klinsmann/go/pkg/mod/gioui.org@v0.0.0-20210228180843-e1248651c871/layout/list.go:111 +0x165
github.com/planetdecred/godcr/ui/decredmaterial.(*Modal).Layout.func2.1.1.1.1(0x0, 0x0, 0x19e, 0x2c1, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, 0x5a13ae0, ...)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/decredmaterial/modal.go:53 +0xc9
gioui.org/layout.Inset.Layout(0x141a00000, 0x141a00000, 0x141a00000, 0x141a00000, 0x0, 0x0, 0x19e, 0x2c1, 0x3f8000003f800000, 0x5071440, ...)
        /Users/klinsmann/go/pkg/mod/gioui.org@v0.0.0-20210228180843-e1248651c871/layout/layout.go:147 +0x4e5
github.com/planetdecred/godcr/ui/decredmaterial.(*Modal).Layout.func2.1.1.1(0x0, 0x0, 0x1c6, 0x2e9, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, 0x5a13ae0, ...)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/decredmaterial/modal.go:52 +0xff
gioui.org/layout.Stack.Layout(0x4bebe00, 0x0, 0x0, 0x1c6, 0x2e9, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, ...)
        /Users/klinsmann/go/pkg/mod/gioui.org@v0.0.0-20210228180843-e1248651c871/layout/stack.go:60 +0x88a
github.com/planetdecred/godcr/ui/decredmaterial.Card.Layout.func1.1(0x0, 0x0, 0x1c6, 0x2e9, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, 0x5a13ae0, ...)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/decredmaterial/card.go:45 +0x260
gioui.org/layout.Inset.Layout(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1c6, 0x2e9, 0x3f8000003f800000, 0x5071440, ...)
        /Users/klinsmann/go/pkg/mod/gioui.org@v0.0.0-20210228180843-e1248651c871/layout/layout.go:147 +0x4e5
github.com/planetdecred/godcr/ui/decredmaterial.Card.Layout.func1(0x0, 0x0, 0x1c6, 0x2e9, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, 0x5a13ae0, ...)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/decredmaterial/card.go:44 +0x133
gioui.org/layout.Stack.Layout(0x4c25100, 0x0, 0x0, 0x1c6, 0x2e9, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, ...)
        /Users/klinsmann/go/pkg/mod/gioui.org@v0.0.0-20210228180843-e1248651c871/layout/stack.go:60 +0x88a
github.com/planetdecred/godcr/ui/decredmaterial.Card.Layout(0x0, 0x0, 0x0, 0x0, 0x41600000ffffffff, 0x4160000041600000, 0xc041600000, 0x0, 0x0, 0x1c6, ...)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/decredmaterial/card.go:42 +0x19a
github.com/planetdecred/godcr/ui/decredmaterial.(*Modal).Layout.func2.1.1(0x0, 0x0, 0x1c6, 0x2e9, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, 0x5a13ae0, ...)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/decredmaterial/modal.go:51 +0x145
gioui.org/layout.Inset.Layout(0x0, 0x43342eaa, 0x0, 0x43342eaa, 0x0, 0x0, 0x1c6, 0x2e9, 0x3f8000003f800000, 0x5071440, ...)
        /Users/klinsmann/go/pkg/mod/gioui.org@v0.0.0-20210228180843-e1248651c871/layout/layout.go:147 +0x4e5
github.com/planetdecred/godcr/ui/decredmaterial.(*Modal).Layout.func2.1(0x0, 0x0, 0x32e, 0x2e9, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, 0x5a13ae0, ...)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/decredmaterial/modal.go:50 +0x101
gioui.org/layout.Direction.Layout(0x4b70408, 0x0, 0x0, 0x32e, 0x2e9, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, ...)
        /Users/klinsmann/go/pkg/mod/gioui.org@v0.0.0-20210228180843-e1248651c871/layout/layout.go:167 +0xce
github.com/planetdecred/godcr/ui/decredmaterial.(*Modal).Layout.func2(0x0, 0x2e9, 0x32e, 0x2e9, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, 0x5a13ae0, ...)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/decredmaterial/modal.go:46 +0x19d
gioui.org/layout.Stack.Layout(0x4c5a900, 0x0, 0x0, 0x32e, 0x2e9, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, ...)
        /Users/klinsmann/go/pkg/mod/gioui.org@v0.0.0-20210228180843-e1248651c871/layout/stack.go:60 +0x88a
github.com/planetdecred/godcr/ui/decredmaterial.(*Modal).Layout(0xc000979bd0, 0x0, 0x0, 0x32e, 0x2e9, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, ...)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/decredmaterial/modal.go:33 +0x2ad
github.com/planetdecred/godcr/ui.(*sendPage).walletAccountSection(0xc000992000, 0x0, 0x0, 0x32e, 0x2e9, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, ...)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/send_page.go:727 +0x1c2
github.com/planetdecred/godcr/ui.(*sendPage).Layout(0xc000992000, 0x0, 0x0, 0x32e, 0x2e9, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, ...)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/send_page.go:372 +0x70a
github.com/planetdecred/godcr/ui.(*Window).SendPage.func1(0x0, 0x0, 0x32e, 0x2e9, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, 0x5a13ae0, ...)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/send_page.go:276 +0xe3
gioui.org/layout.Stack.Layout(0x4bec401, 0x32e, 0x2e9, 0x32e, 0x2e9, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, ...)
        /Users/klinsmann/go/pkg/mod/gioui.org@v0.0.0-20210228180843-e1248651c871/layout/stack.go:60 +0x88a
github.com/planetdecred/godcr/ui/decredmaterial.(*Theme).Background(0xc0004ac100, 0x32e, 0x2e9, 0x32e, 0x2e9, 0x3f8000003f800000, 0x5071440, 0xc0007f6490, 0xc010d192ad163c80, 0xb90eee3257, ...)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/decredmaterial/theme.go:128 +0x23d
github.com/planetdecred/godcr/ui.(*Window).Loop(0xc000442160, 0xc00011bd40)
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/ui/window.go:237 +0x61d
created by main.main
        /Users/klinsmann/go/src/github.com/raedahgroup/godcr/main.go:128 +0x657

### PR DESCRIPTION
**Pull request by hydra0210**
This fixes the bug that crashes the app on the send page after a new account is created. 

Fixes #358

### CODE REVIEW

File: ui/compontents.go [hunk 1]
```diff
@@ -676,6 +676,20 @@ func (page *pageCommon) walletInfoPopup(gtx layout.Context) layout.Dimensions {
 	})
 }
 
+func (page pageCommon) addAccount(account walletAccount) {
+	account.evt = &gesture.Click{}
+
+	if len(page.wallAcctSelector.walletAccounts.selectSendAccount) > account.walletIndex {
+		account.accountIndex = len(page.wallAcctSelector.walletAccounts.selectSendAccount[account.walletIndex])
```
Comment (oshorefueled) [inline ui/compontents.go]: `page.wallAcctSelector.selectedSendWallet` and `page.wallAcctSelector.selectedSendAccount` can be assigned to variables to make the lines shorter horizontally and easier to read.

**Review by oshorefueled — CHANGES_REQUESTED** [review]

**Review by oshorefueled — APPROVED** [review]
