### PR TITLE
Disable disconnect button when clicked.

### LINKED ISSUE #724: Disable disconnect button/update status during disconnection
Sometimes it takes few seconds for godcr to disconnect from the network. Without any visual update that godcr is disconnecting from the network and with the disconnect button remaining active. If the user isn't looking at the log, the user is likely to click disconnect again with the assumption that the software did not register the previous click. The button is active so each click sends a new command to dcrlibwallet. Fast successive clicks will create a condition where:

- dcrlibwallet receives multiple disconnect command, but disconnects successfully.
- It disconnects and immediately reconnect to the network, because between clicks disconnect button state changed but the user did not realize that.  Possibly related to  #385 

In the video below, I clicked the disconnect button multiple times to reproduce the condition described above. Observe the command window underneath godcr and see the clicks register on the log. Also observe godcr disconnect button state.

https://user-images.githubusercontent.com/4796738/146572487-37a580b1-1ef8-4faf-80df-18fdfe69885f.mp4

### PR DESCRIPTION
**Pull request by crux25**
This PR fixes #724 and #385
Summary if issue fixed. If disconnect button isn't disabled after it is clicked it leads to a condition where it is possible to click it again and create another disconnect request. The issue is documented in #724 .

### CODE REVIEW

File: ui/page/overview/sync_details.go [hunk 1]
```diff
@@ -64,6 +64,12 @@ func (pg *AppOverviewPage) syncStatusTextRow(gtx layout.Context, inset layout.In
 		return layout.Flex{Axis: layout.Horizontal, Spacing: layout.SpaceBetween}.Layout(gtx,
 			layout.Flexed(1, syncStatusLabel.Layout),
 			layout.Rigid(func(gtx C) D {
+
+				// Set gxt to Disabled (Sets Queue to nil) if syncClickable state is disabled, prevents double click.
+				if !pg.syncClickable.Enabled {
+					gtx = gtx.Disabled()
+				}
```
Comment (Sirmorrison) [inline ui/page/overview/sync_details.go]: Why not handle the disabled functionality from the clickable widget? `pg.syncClicable.SetEnable(enabled bool)`

File: ui/page/overview/overview_layout.go [hunk 2]
```diff
@@ -247,7 +247,18 @@ func (pg *AppOverviewPage) Handle() {
 		if pg.rescanningBlocks {
 			pg.WL.MultiWallet.CancelRescan()
 		} else {
-			go pg.ToggleSync()
+			// If connected to the Decred network disable button. Prevents multiple clicks.
+			if pg.isConnnected {
+				pg.syncClickable.Enabled = false
+			}
```
Comment (Sirmorrison) [inline ui/page/overview/overview_layout.go]:
```suggestion
			if pg.isConnnected {
				pg.syncClickable.SetEnabled(false)
			}
```

**Review by Sirmorrison — DISMISSED** [review]
It is better to handle the state from the widget so we dont need to repeat this for all pages that may need the clickable widget disabled or enabled state.

File: ui/page/overview/sync_details.go (hunk 1 above)
Comment (crux25) [reply ui/page/overview/sync_details.go]: Nice idea, I had thought about that but realised it require heavy modification of the widget.

**Review by dreacot — APPROVED** [review]
