### PR TITLE
fix seed backup navigation bug

### LINKED ISSUE #791: Confirmation button for seed words on backup seed words screen not working
It is currently not possible to dismiss the "I have written down all 33 seed words" dialog box on a new wallet initial creation.

Seed Button
 
Button responds to click but window does not close. It is possible to get out of window by clicking overview, but wallet backup flag is never cleared.

### PR DESCRIPTION
**Pull request by Sirmorrison**
This PR fix #791 
Fix seed backup navigation bug.

### CODE REVIEW

File: ui/page/main_page.go [hunk 1]
```diff
@@ -450,6 +450,7 @@ func (mp *MainPage) changeFragment(page load.Page) {
 
 	page.OnNavigatedTo()
 	mp.currentPage = page
+
```
Comment (dreacot) [inline ui/page/main_page.go]: Is this line necessary?

**Review by dreacot — APPROVED** [review]
