### PR TITLE
Fix navigation to transaction details

### LINKED ISSUE #151: Can not access to Transaction details on Overview and Transactions Page
### Describe the bug
Can not access to Transaction details on Overview and Transactions Page

### To Reproduce
 - On page Overview & Transactions page
 - Click on Transaction row

### Expected behavior
Should show Transaction details page

### Platform

[ ] Linux

[ ] MacOS

[ ] Windows

### PR DESCRIPTION
**Pull request by song50119**
Resolve #151

### CODE REVIEW

**Comment by oshorefueled** [comment]
The "Included in block" field can just be blank for pending transactions, It shouldn't be "-1"

Screenshot 2020-06-19 at 7 37 46 AM

**Comment by oshorefueled** [comment]
The date of a transaction shouldn't be pending. 

Screenshot 2020-06-22 at 10 20 22 AM

File: ui/transactions_page.go [hunk 1]
```diff
@@ -261,10 +262,9 @@ func (page *transactionsPage) Handle(common pageCommon) {
 
 func initTxnWidgets(common *pageCommon, transaction *wallet.Transaction, txWidgets *transactionWdg) {
 	txWidgets.amount = common.theme.Label(unit.Dp(16), transaction.Balance)
-	txWidgets.time = common.theme.Body1("Pending")
+	txWidgets.time = common.theme.Body1(dcrlibwallet.ExtractDateOrTime(transaction.Txn.Timestamp))
```
Comment (oshorefueled) [inline ui/transactions_page.go]: you can have the "DateTime" added directly to the Transaction data type. That way, you can use it in the layout without calling the ExtractDateOrTime method.

**Review by oshorefueled — CHANGES_REQUESTED** [review]

**Review by oshorefueled — APPROVED** [review]
