### PR TITLE
Fix multiple instace of page on backstack

### LINKED ISSUE #723: Multiple click on Send/Recieve Buttons opens multiple instances of the corresponding pages.
Repeatedly clicking on send/receive button causes the application to open multiple instances of send/receive page. 
This incurs computational/memory cost. This pages should use a singleton design, so there is at most a single instance of this page at any time. See video below.

https://user-images.githubusercontent.com/4796738/146556130-d747984f-8697-4fe4-8df4-3b671a3adb56.mp4

### PR DESCRIPTION
**Pull request by crux25**
This PR closes #723 And fixes the cases where there multiple instances of same page on the backstack.

https://user-images.githubusercontent.com/4796738/147747108-fb6a5153-ed1f-4f47-b533-574b6d2f2477.mp4

### CODE REVIEW

File: ui/page/main_page.go [hunk 1]
```diff
@@ -385,6 +389,23 @@ func (mp *MainPage) currentPageID() string {
 }
 
 func (mp *MainPage) changeFragment(page load.Page) {
+
+	// If Page is the last in back stack return.
+	if mp.currentPageID() == page.ID() {
+		return
+	}
+
+	// Maintian one pointer to Page in backstack slice.
```
Comment (dreacot) [inline ui/page/main_page.go]:
```suggestion
	// Maintain one pointer to Page in backstack slice.
```

**Review by dreacot — DISMISSED** [review]

File: ui/page/main_page.go (hunk 1 above)
Comment (dreacot) [reply ui/page/main_page.go]: @crux25 please fix this typo so we can merge

**Review by dreacot — APPROVED** [review]
