### PR TITLE
Fix inaccurate wallet balance on send page

### LINKED ISSUE #149: inaccurate wallet balance on send page on page switch
### Describe the bug
send page shows an inaccurate balance when the wallet tab is switched on the receive page.

### To Reproduce
* Launch the app
* open the receive page then switch to another wallet
* open the send page

### Expected behavior
The send page should display an accurate balance of each wallet at all times

### Actual behavior
Currently, It displays the balance of another wallet. 

### Additional context
sendpage-bug-gif

### PR DESCRIPTION
**Pull request by song50119**
Resolve #149 

Page's wallet didn't update state when the wallet tabs at other pages switched
Also the Send Page implements it own walletTabs, accountTabs, this isn't consistent with other, eg: Recive, Transactions Pages
PR implements walletsTab, accountTabs from pageCommon upstream

### CODE REVIEW

**Comment by oshorefueled** [comment]
Send page content seem to be suddenly right aligned

Screenshot 2020-06-19 at 12 07 32 AM

File: ui/send_page.go [hunk 1]
```diff
@@ -222,72 +219,16 @@ func (pg *SendPage) Handle(common pageCommon) {
...
-	}
-	pg.accountsTab.SetTabs(accounts)
-}
-
 func (pg *SendPage) Layout(common pageCommon) {
 	if len(common.info.Wallets) == 0 {
-		// show no wallets message
+		common.Layout(common.gtx, func() {
+			layout.Center.Layout(common.gtx, func() {
+				common.theme.H3("No wallet loaded").Layout(common.gtx)
```
Comment (oshorefueled) [inline ui/send_page.go]: When there's no wallet loaded, the app automatically displays the "create wallet" page. Or is there a behaviour that needs this?

**Review by oshorefueled — CHANGES_REQUESTED** [review]

**Review by oshorefueled — APPROVED** [review]
