### PR TITLE
Fix app crash bug when wallet is deleted

### LINKED ISSUE #793: App crashes on wallet deletion
When I attempt to remove a wallet from my device, GoDCR crashes with the error log below returned in the terminal:
This issue has been reproduced on Ubuntu, Fedora and Windows.

`goroutine 10 [running]:
decred.org/dcrwallet/v2/wallet.(*Wallet).AccountBalance(0xc000453408, {0x1bd83b8, 0xc0083e6140}, 0x18e2dd80, 0xc0)
	/home/devchoplife/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.0-rc3/wallet/wallet.go:1907 +0xc9
github.com/planetdecred/dcrlibwallet.(*Wallet).GetAccountBalance(0xc00025a3c0, 0x1bd83b8)
	/home/devchoplife/go/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.6.2-0.20220203081357-951ce632e9d2/accounts.go:108 +0xe6
github.com/planetdecred/dcrlibwallet.(*Wallet).GetAccountsRaw(0xc00025a3c0)
	/home/devchoplife/go/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.6.2-0.20220203081357-951ce632e9d2/accounts.go:41 +0x1b4
github.com/planetdecred/godcr/ui/page.(*MainPage).CalculateTotalWalletsBalance(0xc0000c8540)
	/home/devchoplife/GitRepos/godcr/ui/page/main_page.go:257 +0x7b
github.com/planetdecred/godcr/ui/page.(*MainPage).UpdateBalance(0xc000188a80, 0x20)
	/home/devchoplife/GitRepos/godcr/ui/page/main_page.go:235 +0xd5
github.com/planetdecred/godcr/ui/page.(*MainPage).Layout(0xc000188a80, {{{0x0, 0x0}, {0x3ff, 0x344}}, {0x3f800000, 0x3f800000}, {0x1bae680, 0xc00003e518}, {0xc07d98dca681f1fa, ...}, ...})
	/home/devchoplife/GitRepos/godcr/ui/page/main_page.go:500 +0x38
gioui.org/layout.Stack.Layout({0x30}, {{{0x3ff, 0x344}, {0x3ff, 0x344}}, {0x3f800000, 0x3f800000}, {0x1bae680, 0xc00003e518}, {0xc07d98dca681f1fa, ...}, ...}, ...)
	/home/devchoplife/go/pkg/mod/gioui.org@v0.0.0-20211011183043-05f0f5c20f45/layout/stack.go:60 +0x895
github.com/planetdecred/godcr/ui.(*Window).drawWindowUI(0xc0003c5cc0, {{{0x3ff, 0x344}, {0x3ff, 0x344}}, {0x3f800000, 0x3f800000}, {0x1bae680, 0xc00003e518}, {0xc07d98dca681f1fa, ...}, ...})
	/home/devchoplife/GitRepos/godcr/ui/window.go:254 +0x3d9
github.com/planetdecred/godcr/ui.(*Window).displayWindow(0xc0003c5cc0, {{0xc07d98dca681f1fa, 0xb9fcf4773a, 0x2825bc0}, {0x3f800000, 0x3f800000}, {0x3ff, 0x344}, {{0x0, 0x0}, ...}, ...})
	/home/devchoplife/GitRepos/godcr/ui/window.go:217 +0x16c
github.com/planetdecred/godcr/ui.(*Window).HandleEvents(0xc0003c5cc0)
	/home/devchoplife/GitRepos/godcr/ui/window.go:180 +0x10c
main.main.func2()
	/home/devchoplife/GitRepos/godcr/main.go:80 +0x26
created by main.main
	/home/devchoplife/GitRepos/godcr/main.go:79 +0x4d8`

Below is the link to a video that shows how to reproduce the bug:
https://streamable.com/srzm0u

### PR DESCRIPTION
**Pull request by Sirmorrison**
Fix #793
- add usd balance refresh/retry capability
- clean up code

### CODE REVIEW

File: ui/page/send/page.go [hunk 1]
```diff
@@ -163,34 +166,51 @@ func (pg *Page) OnNavigatedTo() {
...
-		var dcrUsdtBittrex load.DCRUSDTBittrex
+	var dcrUsdtBittrex load.DCRUSDTBittrex
+	errText := "failed to fetch dcrUsdtBittrex value"
+	attempts, err := components.RetryFunc(components.RetryAttempts, 2*time.Second, func() error {
 		err := load.GetUSDExchangeValue(&dcrUsdtBittrex)
 		if err != nil {
-			pg.exchangeError = err.Error()
-			return
+			if strings.Contains(err.Error(), "no such host") {
+				pg.exchangeError = "Exchange rate not fetched. Kinly check internet connection. Retrying..."
```
Comment (devchoplife) [inline ui/page/send/page.go]:
```suggestion
				pg.exchangeError = "Exchange rate not fetched. Kindly check internet connection. Retrying..."
```

**Review by devchoplife — CHANGES_REQUESTED** [review]

File: ui/load/load.go [hunk 2]
```diff
@@ -83,6 +83,8 @@ type Load struct {
 	SubscribeKeyEvent   func(eventChan chan *key.Event, pageID string) // Widgets call this function to recieve key events.
 	UnsubscribeKeyEvent func(pageID string) error
 	ReloadApp           func()
+
+	IsCurrencySettingUpdated bool
```
Comment (itswisdomagain) [inline ui/load/load.go]: Concerned about this. Not sure why this should be this global. Revisit.

File: ui/page/components/utils.go [hunk 3]
```diff
@@ -1,6 +1,13 @@
...
 
-import "context"
+import (
+	"context"
+	"fmt"
+	"log"
+	"time"
+)
+
+var RetryAttempts = 7
```
Comment (itswisdomagain) [inline ui/page/components/utils.go]: This isn't used here, perhaps this isn't the best/right place to define this.

File: ui/page/components/utils.go [hunk 4]
```diff
@@ -12,3 +19,18 @@ func ContextDone(ctx context.Context) bool {
 		return false
 	}
 }
+
+func RetryFunc(attempts int, sleep time.Duration, errFunc func() error) (att int, err error) {
```
Comment (itswisdomagain) [inline ui/page/components/utils.go]: - Needs a comment.
- Also `errFunc` -> `runFunc`, it mustn't return an error, it may return a nil error which is valid.
- `att` is never used/assigned. Remove the named return variables and instead declare a `var err error` before the for loop below.

File: ui/page/components/utils.go [hunk 5]
```diff
@@ -12,3 +19,18 @@ func ContextDone(ctx context.Context) bool {
...
+	for i := 0; i < attempts; i++ {
+		if i > 0 {
+			log.Println("retrying after error:", err)
+			time.Sleep(sleep)
+			sleep *= 2
```
Comment (itswisdomagain) [inline ui/page/components/utils.go]: I'd reorder this, this way (PS: for logging purposes, it'd be helpful to pass a `funcDesc string` parameter that can be used in the suggested log below, I also renamed `sleep` to `sleepDur`):
```suggestion
			sleepDur *= i
			log.Println("waiting %s to retry function %s after error: %v", sleepDur, funcDesc, err)
			time.Sleep(sleepDur)
```

File: ui/page/components/utils.go [hunk 6]
```diff
@@ -12,3 +19,18 @@ func ContextDone(ctx context.Context) bool {
...
+		}
+		err = errFunc()
+		if err == nil {
+			return -1, nil
```
Comment (itswisdomagain) [inline ui/page/components/utils.go]: `return i, nil`?

File: ui/page/components/utils.go [hunk 7]
```diff
@@ -12,3 +19,18 @@ func ContextDone(ctx context.Context) bool {
...
+		}
+	}
+	return attempts, fmt.Errorf("after %d attempts, last error: %s", attempts, err)
```
Comment (itswisdomagain) [inline ui/page/components/utils.go]: Depending on how this returned error is used, this message might not be clear enough.

File: ui/page/main_page.go [hunk 8]
```diff
@@ -59,12 +63,16 @@ type MainPage struct {
 	sendPage      *send.Page   // reuse value to keep data persistent onresume.
 	receivePage   *ReceivePage // pointer to receive page. to avoid duplication.
 
+	loader       material.LoaderStyle
+	refreshValue *decredmaterial.Clickable
```
Comment (itswisdomagain) [inline ui/page/main_page.go]: Is `loader` a page loader or specific to some page element? The name can use some love.
`refreshValue` is a clickable that refreshes a value? Perhaps `refreshExchangeRateBtn`?

File: ui/page/main_page.go [hunk 9]
```diff
@@ -218,20 +231,51 @@ func (mp *MainPage) OnNavigatedTo() {
 			go mp.WL.MultiWallet.Politeia.Sync()
 		}
 	}
+
+	mp.updateExchangeSetting()
+
+	mp.UpdateBalance()
```
Comment (itswisdomagain) [inline ui/page/main_page.go:229]: Does fetching the balance take time? If it doesn't, this should be in `OnNavigatedTo` since it doesn't make sense to fetch the balance when the page isn't being displayed yet, while it makes sense to refresh the balance whenever the page is about to be displayed.

File: ui/page/main_page.go [hunk 10]
```diff
@@ -218,20 +231,51 @@ func (mp *MainPage) OnNavigatedTo() {
...
+func (mp *MainPage) updateExchangeSetting() {
 	currencyExchangeValue := mp.WL.Wallet.ReadStringConfigValueForKey(dcrlibwallet.CurrencyConversionConfigKey)
 	mp.usdExchangeSet = currencyExchangeValue == values.USDExchangeValue
+	if mp.usdExchangeSet {
+		go mp.fetchExchangeValue()
+	}
+}
+
+func (mp *MainPage) fetchExchangeValue() {
+	attempts, err := components.RetryFunc(components.RetryAttempts, 2*time.Second, func() error {
```
Comment (itswisdomagain) [inline ui/page/main_page.go]: It doesn't make much sense to me for `components` to have a `RetryAttempts` property - how many times something should be retried is best defined by the caller of the function. I'd rather declare and use a `const fetchExchangeRateRetries` field in this file.

File: ui/page/main_page.go [hunk 11]
```diff
@@ -218,20 +231,51 @@ func (mp *MainPage) OnNavigatedTo() {
...
-	}
+func (mp *MainPage) updateExchangeSetting() {
 	currencyExchangeValue := mp.WL.Wallet.ReadStringConfigValueForKey(dcrlibwallet.CurrencyConversionConfigKey)
 	mp.usdExchangeSet = currencyExchangeValue == values.USDExchangeValue
+	if mp.usdExchangeSet {
+		go mp.fetchExchangeValue()
+	}
+}
+
+func (mp *MainPage) fetchExchangeValue() {
```
Comment (itswisdomagain) [inline ui/page/main_page.go]:
```suggestion
func (mp *MainPage) fetchExchangeRate() {
```

File: ui/page/main_page.go [hunk 12]
```diff
@@ -218,20 +231,51 @@ func (mp *MainPage) OnNavigatedTo() {
...
+
+	if err != nil || mp.dcrUsdtBittrex.LastTradeRate == "" {
+		log.Error(err)
+
+		if attempts == components.RetryAttempts {
+			mp.isLoadingUSDValue = false
+		}
+		return
+	}
+}
```
Comment (itswisdomagain) [inline ui/page/main_page.go]: I initially had a few thoughts about this method, found it easier to just recommend an alternative snippet:
```
func (mp *MainPage) fetchExchangeValue() {
	if mp.isLoadingUSDValue {
		return
	}
	maxAttempts := 7
	delayBtwAttempts := 2 * time.Second
	mp.isLoadingUSDValue = true
	attempts, err := components.RetryFunc(maxAttempts, delayBtwAttempts, func() error {
		return load.GetUSDExchangeValue(&mp.dcrUsdtBittrex)
	})
	if err != nil {
		log.Errorf("error fetching usd exchange rate value after %d attempts: %v", attempts, err)
	} else if mp.dcrUsdtBittrex.LastTradeRate == "" {
		log.Errorf("no error while fetching usd exchange rate in %d tries, but no rate was fetched", attempts)
	} else {
		log.Infof("exchange rate value fetched: %s", mp.dcrUsdtBittrex.LastTradeRate)
		mp.UpdateBalance()
		mp.RefreshWindow()
	}
	mp.isLoadingUSDValue = false
}
```

File: ui/page/main_page.go [hunk 13]
```diff
@@ -313,10 +357,19 @@ func (mp *MainPage) UnlockWalletForSyncing(wal *dcrlibwallet.Wallet) {
 // displayed.
 // Part of the load.Page interface.
 func (mp *MainPage) HandleUserInteractions() {
+	if mp.IsCurrencySettingUpdated {
```
Comment (itswisdomagain) [inline ui/page/main_page.go]: Not sure what is meant by `currency setting`, this name needs some love at least. Also, a global variable of this form to track when a particular setting is changed doesn't sound good. Will propose something later.

File: ui/page/main_page.go [hunk 14]
```diff
@@ -313,10 +357,19 @@ func (mp *MainPage) UnlockWalletForSyncing(wal *dcrlibwallet.Wallet) {
...
+		mp.updateExchangeSetting()
+		mp.IsCurrencySettingUpdated = false
+	}
+
 	if mp.currentPage != nil {
 		mp.currentPage.HandleUserInteractions()
 	}
 
+	if mp.refreshValue.Clicked() && mp.usdExchangeSet {
```
Comment (itswisdomagain) [inline ui/page/main_page.go]: Would there even be a refresh button to click if the exchange rate setting isn't configured?
```suggestion
	if mp.refreshValue.Clicked() {
```

File: ui/page/main_page.go [hunk 15]
```diff
@@ -554,31 +606,47 @@ func (mp *MainPage) Layout(gtx layout.Context) layout.Dimensions {
...
-				})
+	switch {
+	case mp.usdExchangeSet && mp.isLoadingUSDValue && mp.dcrUsdtBittrex.LastTradeRate == "":
+		gtx.Constraints.Max.Y = gtx.Px(values.MarginPadding18)
+		gtx.Constraints.Max.X = gtx.Constraints.Max.Y
+		return layout.Inset{
+			Top:  values.MarginPadding8,
+			Left: values.MarginPadding5,
+		}.Layout(gtx, func(gtx C) D {
+			return mp.loader.Layout(gtx)
```
Comment (itswisdomagain) [inline ui/page/main_page.go]: Instead of having a `mp.loader` property always assigned and ready, which may never be used or will not be needed after some point, create the loader object here and lay it out - strictly when needed.
```suggestion
			loader := material.NewTheme(gofont.Collection()).Loader(mp.Theme)
			return loader.Layout(gtx)
```

File: ui/page/main_page.go [hunk 16]
```diff
@@ -554,31 +606,47 @@ func (mp *MainPage) Layout(gtx layout.Context) layout.Dimensions {
...
-						Right:  values.MarginPadding6,
-					}
-					return border.Layout(gtx, func(gtx C) D {
-						return padding.Layout(gtx, func(gtx C) D {
-							return mp.Theme.Body2(mp.totalBalanceUSD).Layout(gtx)
-						})
-					})
-				})
+	switch {
+	case mp.usdExchangeSet && mp.isLoadingUSDValue && mp.dcrUsdtBittrex.LastTradeRate == "":
```
Comment (itswisdomagain) [inline ui/page/main_page.go]: Seems all the cases require `mp.usdExchangeSet`. Can remove that condition from all the cases and do this before the switch:
```
if !mp.usdExchangeSet { return D{} }
```

File: ui/page/main_page.go [hunk 17]
```diff
@@ -554,31 +606,47 @@ func (mp *MainPage) Layout(gtx layout.Context) layout.Dimensions {
...
+	case mp.usdExchangeSet && !mp.isLoadingUSDValue && mp.dcrUsdtBittrex.LastTradeRate == "":
+		return layout.Inset{
+			Top:  values.MarginPadding7,
+			Left: values.MarginPadding5,
+		}.Layout(gtx, func(gtx C) D {
+			return mp.refreshValue.Layout(gtx, func(gtx C) D {
+				return mp.Icons.Restore.Layout16dp(gtx)
+			})
+		})
+	case mp.usdExchangeSet && mp.dcrUsdtBittrex.LastTradeRate != "" && len(mp.totalBalanceUSD) > 0:
```
Comment (itswisdomagain) [inline ui/page/main_page.go]: Looks like this should only be concerned with `len(mp.totalBalanceUSD) > 0` - display the USD amount as long as it is already calculated.
```suggestion
	case len(mp.totalBalanceUSD) > 0:
```

**Review by itswisdomagain — CHANGES_REQUESTED** [review]
First pass. Will re-review after these.

File: ui/load/load.go (hunk 2 above)
Comment (Sirmorrison) [reply ui/load/load.go]: need the info here to update the main page from list_preference.go

File: ui/page/components/utils.go (hunk 3 above)
Comment (Sirmorrison) [reply ui/page/components/utils.go]: Why so is i didnt want to re-declare same for the individual pages. (send page and main page)

File: ui/load/load.go (hunk 2 above)
Comment (itswisdomagain) [reply ui/load/load.go]: I saw this, works for now but isn't ideal. I made a related comment below.

File: ui/page/components/utils.go (hunk 3 above)
Comment (itswisdomagain) [reply ui/page/components/utils.go]: I recommended an alternative in the main page that can also apply to the send page. This is one scenario where duplication is okay.

File: ui/page/main_page.go (hunk 9 above)
Comment (Sirmorrison) [reply ui/page/main_page.go:229]: it is currently in the `OnNavigatedTo()`

File: ui/page/components/utils.go (hunk 5 above)
Comment (Sirmorrison) [reply ui/page/components/utils.go]: `sleepDur *= i` `i` does not work... Mismatch type.

File: ui/page/components/utils.go [hunk 18]
```diff
@@ -12,3 +17,22 @@ func ContextDone(ctx context.Context) bool {
 		return false
 	}
 }
+
+// RetryFunc implement retry policy for processes that needs to be executed
+// in the background after initial failure.
```
Comment (itswisdomagain) [inline ui/page/components/utils.go]: This function doesn't execute any process in the background. This comment could be (is) misleading.

File: ui/page/components/utils.go [hunk 19]
```diff
@@ -12,3 +17,22 @@ func ContextDone(ctx context.Context) bool {
...
+func RetryFunc(retryAttempts int, sleepDur time.Duration, errFunc func() error) (int, error) {
+	var err error
+	for i := 0; i < retryAttempts; i++ {
+		if i > 0 {
+			sleepDur *= 2
```
Comment (itswisdomagain) [inline ui/page/components/utils.go]:
```suggestion
			sleepDur *= (2-i)
```
So when i == 1, sleepDur is sleepDur *= 1 and only begins to increase when i > 1.

File: ui/page/components/utils.go [hunk 20]
```diff
@@ -12,3 +17,22 @@ func ContextDone(ctx context.Context) bool {
...
+			log.Printf("waiting %v to retry after error: %v", sleepDur, err)
```
Comment (itswisdomagain) [inline ui/page/components/utils.go]: To retry what? This wouldn't be a very helpful log message. A previous review comment recommended adding a `funcDesc` parameter to this function which can be included in this log for better clarity.

File: ui/page/main_page.go (hunk 9 above)
Comment (itswisdomagain) [reply ui/page/main_page.go:229]: Then we certainly don't need it here. Any balance calculated here will not be displayed until `OnNavigatedTo` is called and that will re-calculate the balance.

File: ui/page/send/layout.go [hunk 21]
```diff
@@ -276,11 +278,17 @@ func (pg *Page) toSection(gtx layout.Context) layout.Dimensions {
 					layout.Rigid(func(gtx C) D {
 						return layout.Flex{Axis: layout.Horizontal}.Layout(gtx,
 							layout.Rigid(func(gtx C) D {
-								label := pg.Theme.Body2("Exchange rate not fetched")
+								label := pg.Theme.Body2(pg.exchangeError)
```
Comment (itswisdomagain) [inline ui/page/send/layout.go]: This should just be `"Exchange rate not fetched. Check internet connection."` I explain why below.

File: ui/page/send/layout.go [hunk 22]
```diff
@@ -276,11 +278,17 @@ func (pg *Page) toSection(gtx layout.Context) layout.Dimensions {
...
 								label.Color = pg.Theme.Color.Danger
+								if strings.Contains(pg.exchangeError, "Retrying") {
+									label.Color = pg.Theme.Color.Primary
+								}
 								return label.Layout(gtx)
 							}),
 							layout.Rigid(func(gtx C) D {
+								if strings.Contains(pg.exchangeError, "Retrying") {
```
Comment (itswisdomagain) [inline ui/page/send/layout.go]: Sounds like you need a `pg.isFetchingExchangeRate` bool property, as you have in the mainpage. I see that `pg.exchangeError` is set for each failed attempt but the set error message may not show up on the UI without a `RefreshWindow` call. I think you should display a loader or some brief _`fetching exchange rate`_ text while the fetching is ongoing instead of showing an error message for each failed try. At the end of all tries, `if !pg.isFetchingExchangeRate && (the rate isn't ready)`, you can then show the message I recommended above.

File: ui/page/send/page.go [hunk 23]
```diff
@@ -163,34 +166,54 @@ func (pg *Page) OnNavigatedTo() {
...
+	errText := "failed to fetch dcrUsdtBittrex value"
+
+	maxAttempts := 7
+	delayBtwAttempts := 2 * time.Second
+	attempts, err := components.RetryFunc(maxAttempts, delayBtwAttempts, func() error {
 		err := load.GetUSDExchangeValue(&dcrUsdtBittrex)
 		if err != nil {
-			pg.exchangeError = err.Error()
-			return
+			if strings.Contains(err.Error(), "no such host") {
```
Comment (itswisdomagain) [inline ui/page/send/page.go]: This string comparison is not reliable, best to do without it and always assume internet connection issues. Secondly, no need to display an error message each time `load.GetUSDExchangeValue` returns an error. Just return the error and let the retrials continue to  happen in the background. Only show an error message when the rate cannot be fetched after the maxAttempts.

**Review by itswisdomagain — CHANGES_REQUESTED** [review]
The send page's `fetchExchangeRate()` should be a lot more like the recently modified main page method of the same name.

File: ui/page/components/utils.go (hunk 19 above)
Comment (Sirmorrison) [reply ui/page/components/utils.go]: it does not work getting the following error. `invalid operation: sleepDur *= 2 - i (mismatched types time.Duration and int)`

using `time.Duration(2 - i)` results to 0s.

File: ui/page/main_page.go (hunk 9 above)
Comment (Sirmorrison) [reply ui/page/main_page.go:229]: From my understanding, want to be able to update the balance when the page loads, and when there is an update from a listener. 

Moving this from `OnNavigatedTo`, i am not sure where else to place it. You can review the update i did if it works.

Comment (itswisdomagain) [reply ui/page/main_page.go:229]: Oy my, missed the fact that is in `OnNavigatedTo`. Sorry, it's fine here.

File: ui/page/components/utils.go [hunk 24]
```diff
@@ -12,3 +17,22 @@ func ContextDone(ctx context.Context) bool {
...
 	}
 }
+
+// RetryFunc implement retry policy for processes that needs to be executed
+// the after initial failure.
+func RetryFunc(retryAttempts int, sleepDur time.Duration, funcDesc string, errFunc func() error) (int, error) {
+	var err error
+	for i := 0; i < retryAttempts; i++ {
+		if i > 0 {
+			sleepDur *= 2
```
Comment (itswisdomagain) [inline ui/page/components/utils.go]: Then surround this with an if statement:
```suggestion
			if i > 1 { sleepDur *= 2 }
```

File: ui/page/send/page.go [hunk 25]
```diff
@@ -163,34 +166,49 @@ func (pg *Page) OnNavigatedTo() {
...
+		pg.ExchangeRateMassage = ""
 		exchangeRate, err := strconv.ParseFloat(dcrUsdtBittrex.LastTradeRate, 64)
 		if err != nil {
-			pg.exchangeError = err.Error()
+			pg.ExchangeRateMassage = err.Error()
 			return
 		}
 
-		pg.exchangeError = ""
+		pg.ExchangeRateMassage = ""
```
Comment (itswisdomagain) [inline ui/page/send/page.go]: Already cleared above.

File: ui/page/send/page.go [hunk 26]
```diff
@@ -54,12 +56,13 @@ type Page struct {
...
+	moreOptionIsOpen       bool
+	isFetchingExchangeRate bool
 
-	exchangeRate   float64
-	usdExchangeSet bool
-	exchangeError  string
-	confirmTxModal *sendConfirmModal
+	exchangeRate        float64
+	usdExchangeSet      bool
+	ExchangeRateMassage string
```
Comment (itswisdomagain) [inline ui/page/send/page.go]:
```suggestion
	exchangeRateMessage string
```

File: ui/preference/list_preference.go [hunk 27]
```diff
@@ -108,6 +108,9 @@ func (lp *ListPreferenceModal) Handle() {
 		lp.currentValue = lp.optionsRadioGroup.Value
 		lp.wallet.SaveConfigValueForKey(lp.preferenceKey, lp.optionsRadioGroup.Value)
 		lp.updateButtonClicked()
+		if lp.title == values.StrCurrencyConversion {
+			lp.IsCurrencySettingUpdated = true
+		}
 		lp.DismissModal(lp)
```
Comment (itswisdomagain) [inline ui/preference/list_preference.go]: I think we can do away with the `IsCurrencySettingUpdated` field now. `lp.DismissModal` will trigger a window refresh, which will call the main page's `Layout` method. The main page's layout method can call the `updateExchangeSetting()` method to check if the setting has changed. That method will need to be re-written like this:

```
func (mp *MainPage) updateExchangeSetting() {
	currencyExchangeValue := mp.WL.Wallet.ReadStringConfigValueForKey(dcrlibwallet.CurrencyConversionConfigKey)
	usdExchangeSet := currencyExchangeValue == values.USDExchangeValue
	if mp.usdExchangeSet == usdExchangeSet {
		return // nothing has changed
	}
	mp.usdExchangeSet = usdExchangeSet
	if mp.usdExchangeSet {
		go mp.fetchExchangeRate()
	}
}
```

File: ui/page/main_page.go [hunk 28]
```diff
@@ -218,20 +226,48 @@ func (mp *MainPage) OnNavigatedTo() {
...
+	} else {
+		log.Infof("exchange rate value fetched: %s", mp.dcrUsdtBittrex.LastTradeRate)
+		mp.UpdateBalance()
+		mp.RefreshWindow()
+	}
+	mp.isFetchingExchangeRate = false
+}
 
+func (mp *MainPage) UpdateBalance() {
+	mp.updateExchangeSetting()
```
Comment (itswisdomagain) [inline ui/page/main_page.go]: This isn't necessary here. This only needs to be done when the setting has likely changed. My previous comment recommends making this check in `Layout`.

**Review by itswisdomagain — CHANGES_REQUESTED** [review]

File: ui/page/components/utils.go [hunk 29]
```diff
@@ -12,3 +17,24 @@ func ContextDone(ctx context.Context) bool {
 		return false
 	}
 }
+
+// RetryFunc implement retry policy for processes that needs to be executed
+// the after initial failure.
```
Comment (itswisdomagain) [inline ui/page/components/utils.go]:
```suggestion
// RetryFunc implements retry policy for processes that needs to be executed
// after initial failure.
```

File: ui/page/main_page.go [hunk 30]
```diff
@@ -497,7 +540,7 @@ func (mp *MainPage) popToFragment(pageID string) {
 // to be eventually drawn on screen.
 // Part of the load.Page interface.
 func (mp *MainPage) Layout(gtx layout.Context) layout.Dimensions {
-	mp.UpdateBalance(false)
+	mp.updateExchangeSetting()
```
Comment (itswisdomagain) [inline ui/page/main_page.go]: Let's add a comment here to give future code maintainers an idea why this is being done each time `Layout` is called.
```suggestion
	mp.updateExchangeSetting() // the setting may have changed, leading to this window refresh, let's check
```

File: ui/page/send/page.go [hunk 31]
```diff
@@ -163,34 +166,48 @@ func (pg *Page) OnNavigatedTo() {
...
 		}
 
-		pg.exchangeError = ""
 		pg.exchangeRate = exchangeRate
 		pg.amount.setExchangeRate(exchangeRate)
 		pg.validateAndConstructTx() // convert estimates to usd
-	}()
+		pg.RefreshWindow()
+	}
+	pg.isFetchingExchangeRate = false
```
Comment (itswisdomagain) [inline ui/page/send/page.go]: Call `pg.RefreshWindow()` after setting `pg.isFetchingExchangeRate = false`. This ensures that the updated `pg.exchangeRateMessage` is displayed on the UI even if there was an error fetching the exchange rate.

File: ui/page/send/page.go [hunk 32]
```diff
@@ -163,34 +166,48 @@ func (pg *Page) OnNavigatedTo() {
...
 		if err != nil {
-			pg.exchangeError = err.Error()
+			pg.exchangeRateMessage = err.Error()
 			return
 		}
 
-		pg.exchangeError = ""
 		pg.exchangeRate = exchangeRate
 		pg.amount.setExchangeRate(exchangeRate)
 		pg.validateAndConstructTx() // convert estimates to usd
```
Comment (itswisdomagain) [inline ui/page/send/page.go]: If you return when err != nil, the `isFetchingExchangeRate` value won't be set to false and the window will not refresh to show the new message.
This instead:
```
		if err != nil {
			pg.exchangeRateMessage = err.Error()
		} else {
			pg.exchangeRate = exchangeRate
			pg.amount.setExchangeRate(exchangeRate)
			pg.validateAndConstructTx() // convert estimates to usd
		}
```

File: ui/page/components/utils.go [hunk 33]
```diff
@@ -12,3 +17,24 @@ func ContextDone(ctx context.Context) bool {
...
+func RetryFunc(retryAttempts int, sleepDur time.Duration, funcDesc string, errFunc func() error) (int, error) {
+	var err error
+	for i := 0; i < retryAttempts; i++ {
+		if i > 0 {
+			if i > 1 {
+				sleepDur *= 2
+			}
+			log.Printf("waiting %s to retry function %s after error: %v", sleepDur, funcDesc, err)
```
Comment (itswisdomagain) [inline ui/page/components/utils.go]: Just seeing this, `log` is an imported package. Not sure how it works but it certainly does not use the same logging pattern I've seen in the rest of this godcr codebase. I don't think the components pkg has a logger yet, I think #777 introduces one. This can be `fmt.Printf` for now and should end with a `\n`.

File: ui/page/components/utils.go [hunk 34]
```diff
@@ -12,3 +17,24 @@ func ContextDone(ctx context.Context) bool {
...
+			time.Sleep(sleepDur)
+		}
+		err = errFunc()
+		if err == nil {
+			return i, nil
+		}
+	}
+
+	return retryAttempts, fmt.Errorf("after %d attempts, last error: %s", retryAttempts, err)
```
Comment (itswisdomagain) [inline ui/page/components/utils.go]: This doesn't read well when paired with another message, it currently says `error fetching usd exchange rate value after 3 attempts: after 3 attempts, last error: Get "https://api.bittrex.com/v3/markets/DCR-USDT/ticker": dial tcp: lookup api.bittrex.com: no such host`.

Can omit the number of tries, the caller already knows.
```suggestion
	return retryAttempts, fmt.Errorf("last error: %s", err)
```

File: ui/page/main_page.go [hunk 35]
```diff
@@ -218,20 +226,51 @@ func (mp *MainPage) OnNavigatedTo() {
...
+	if mp.usdExchangeSet {
+		go mp.fetchExchangeRate()
+	}
+}
 
+func (mp *MainPage) fetchExchangeRate() {
+	if mp.isFetchingExchangeRate {
+		return
+	}
+	maxAttempts := 7
```
Comment (itswisdomagain) [inline ui/page/main_page.go]: In testing, this is quite a long time. I've experimented with 3 tries and that seems okay. 3 tries will wait for a total of 6 seconds, aside the time each network call attempt takes. Can experiment with a different figure and see what is better for UX. While we want to try repeatedly, user should know soon enough when it isn't working so they can check their connection. Applies to send page as well.

**Review by itswisdomagain — CHANGES_REQUESTED** [review]

File: ui/page/components/utils.go [hunk 36]
```diff
@@ -12,3 +16,24 @@ func ContextDone(ctx context.Context) bool {
 		return false
 	}
 }
+
+// RetryFunc implements retry policy for processes that needs to be executed
+// the after initial failure.
```
Comment (itswisdomagain) [inline ui/page/components/utils.go]:
```suggestion
// after initial failure.
```

File: ui/page/main_page.go [hunk 37]
```diff
@@ -554,31 +597,51 @@ func (mp *MainPage) Layout(gtx layout.Context) layout.Dimensions {
...
+	}
+	switch {
+	case mp.isFetchingExchangeRate && mp.dcrUsdtBittrex.LastTradeRate == "":
+		gtx.Constraints.Max.Y = gtx.Px(values.MarginPadding18)
+		gtx.Constraints.Max.X = gtx.Constraints.Max.Y
+		return layout.Inset{
+			Top:  values.MarginPadding8,
+			Left: values.MarginPadding5,
+		}.Layout(gtx, func(gtx C) D {
+			loader := material.Loader(material.NewTheme(gofont.Collection()))
```
Comment (itswisdomagain) [inline ui/page/main_page.go]: I jsut remembered we already have a theme!
```suggestion
			loader := material.Loader(mp.Theme.Base)
```

**Review by itswisdomagain — DISMISSED** [review]
2 nits, good to go after these

**Review by dreacot — APPROVED** [review]
LGTM
