### PR TITLE
Watch-only wallet delete bug

### LINKED ISSUE #942: after deleting a watch only wallet, the watch-only section still shows
Screenshot from 2022-05-22 22-16-09

### PR DESCRIPTION
**Pull request by crux25**
This PR fixes the watch-only wallet crash delete bug. Hides watch-only wallet layout after the last watch-only wallet is deleted and shows loader widget to indicate that a process is going on when a watch-only wallet is being deleted.  Closes #942 and #941.

https://user-images.githubusercontent.com/4796738/170577854-4c6324ad-9b1d-4320-ac71-b4b2685bcf58.mp4

### CODE REVIEW

File: ui/modal/info_modal.go [hunk 1]
```diff
@@ -171,22 +183,31 @@ func (in *InfoModal) HandleKeyEvent(evt *key.Event) {
...
+		}
 		isChecked := false
 		if in.checkbox.CheckBox != nil {
 			isChecked = in.checkbox.CheckBox.Value
 		}
 
 		in.positiveButtonClicked(isChecked)
+		if !in.isLoading {
+			in.DismissModal(in)
+		}
```
Comment (Sirmorrison) [inline ui/modal/info_modal.go]: i dont think you need this here again. 
You already return when loading is set on line 186... 
```suggestion
	     in.DismissModal(in)

```

**Review by Sirmorrison — CHANGES_REQUESTED** [review]

File: ui/modal/info_modal.go (hunk 1 above)
Comment (crux25) [reply ui/modal/info_modal.go]: That is needed else modal will always dismiss even when we need to show the loading widget. https://github.com/planetdecred/godcr/blob/84fa15f87dcd236993f5e402a4b56b2e48e28fb5/ui/modal/info_modal.go#L186 this is needed just in case someone is super fast and clicks the button twice before the loading widget is activated.

Comment (Sirmorrison) [reply ui/modal/info_modal.go]: what you have is a for loop meaning for every click, it starts a new instance.

**Review by Sirmorrison — CHANGES_REQUESTED** [review]

File: ui/modal/info_modal.go (hunk 1 above)
Comment (crux25) [reply ui/modal/info_modal.go]: I didn't write the for loop. I only modified it's content. I'll read the connected codes to figure out if for loop is appropriate there.

File: ui/modal/info_modal.go [hunk 2]
```diff
@@ -170,23 +182,32 @@ func (in *InfoModal) HandleKeyEvent(evt *key.Event) {
 }
 
 func (in *InfoModal) Handle() {
-	for in.btnPositve.Clicked() {
-		in.DismissModal(in)
+	if in.btnPositve.Clicked() {
```
Comment (Sirmorrison) [inline ui/modal/info_modal.go]: Kindly revert this.

File: ui/modal/info_modal.go (hunk 1 above)
Comment (Sirmorrison) [reply ui/modal/info_modal.go]: The review was not if you wrote it or if the for loop was wrong... it was for the redundant lines of codes to be removed.

**Review by Sirmorrison — CHANGES_REQUESTED** [review]

**Review by dreacot — DISMISSED** [review]

**Comment by dreacot** [comment]
@Sirmorrison i've approved, kindly confirm if your review still stands before i merge

File: ui/modal/info_modal.go [hunk 3]
```diff
@@ -171,22 +183,28 @@ func (in *InfoModal) HandleKeyEvent(evt *key.Event) {
...
-		in.DismissModal(in)
 		isChecked := false
 		if in.checkbox.CheckBox != nil {
 			isChecked = in.checkbox.CheckBox.Value
 		}
 
 		in.positiveButtonClicked(isChecked)
+		if !in.isLoading {
+			in.DismissModal(in)
+		}
```
Comment (Sirmorrison) [inline ui/modal/info_modal.go]: ideally, i will expect this `isLoading` check to be at the top just before line 186. 
This way, nothing else get executed when there is a process running.
```
if in.isLoading{
     return
}
```

**Review by Sirmorrison — CHANGES_REQUESTED** [review]
Besides the review below, the pr looks good to go.

File: ui/modal/info_modal.go (hunk 3 above)
Comment (crux25) [reply ui/modal/info_modal.go]: This has been a point of confusion, so I'll try to explain in more detail.
https://github.com/planetdecred/godcr/blob/5f9db205405319305acce5ba8b7818a66d7f6ea9/ui/modal/info_modal.go#L192-L194 cannot be placed above https://github.com/planetdecred/godcr/blob/5f9db205405319305acce5ba8b7818a66d7f6ea9/ui/modal/info_modal.go#L191 because this is the called back that's passed to https://github.com/planetdecred/godcr/blob/5f9db205405319305acce5ba8b7818a66d7f6ea9/ui/modal/info_modal.go#L123

Think about it this way. When the positive button is clicked, an event is generated and https://github.com/planetdecred/godcr/blob/5f9db205405319305acce5ba8b7818a66d7f6ea9/ui/modal/info_modal.go#L184 is called. At this point https://github.com/planetdecred/godcr/blob/5f9db205405319305acce5ba8b7818a66d7f6ea9/ui/modal/info_modal.go#L47 is false because the call back passed to https://github.com/planetdecred/godcr/blob/5f9db205405319305acce5ba8b7818a66d7f6ea9/ui/modal/info_modal.go#L123 hasn't been executed. At some point https://github.com/planetdecred/godcr/blob/5f9db205405319305acce5ba8b7818a66d7f6ea9/ui/modal/info_modal.go#L191 -the callback- is executed and https://github.com/planetdecred/godcr/blob/5f9db205405319305acce5ba8b7818a66d7f6ea9/ui/modal/info_modal.go#L47 is true. The consequence of placing that logic above the callback is that the modal will always dismiss before execution is completed - try it!!!. 

The way I figured to prevent double execution is to check if https://github.com/planetdecred/godcr/blob/5f9db205405319305acce5ba8b7818a66d7f6ea9/ui/modal/info_modal.go#L47 is true twice first at the start of https://github.com/planetdecred/godcr/blob/5f9db205405319305acce5ba8b7818a66d7f6ea9/ui/modal/info_modal.go#L184 execution and second after https://github.com/planetdecred/godcr/blob/5f9db205405319305acce5ba8b7818a66d7f6ea9/ui/modal/info_modal.go#L191 -the callback- is executed. That's the point I was trying to get across to you earlier.

Other option is to rewrite https://github.com/planetdecred/godcr/blob/5f9db205405319305acce5ba8b7818a66d7f6ea9/ui/modal/info_modal.go#L123-L127

Comment (Sirmorrison) [reply ui/modal/info_modal.go]: Alright. I think i get your point... you are trying to prevent the modal from dismissing when a process is still running.

Originally, the `positiveButtonClicked` callback just waits for the executable codes in the `PositiveButton()` where ever it is used to complete executing and send a feedback to the button to dismiss.

What we have currently are 2 methods running side by side and really does not need one to finish before the second one starts.

Before now, it was just an info modal and really was not designed what what we used it for. Hence the reason for the initial implementation as the `positiveButtonClicked` tend to execute completely before the modl dismisses.

That not withstanding, what we needed to have done was have the `positiveButtonClicked` function like that on the password modal. Have it return a `bool` value on then does the modal dismiss.

But we should check the `isLoading` at the top level on button click and return.

```
if positiveButtonClicked() {
   Dismiss()
}
```

Comment (crux25) [reply ui/modal/info_modal.go]: That was my thought initially but I have to keep the task withing scope. I'll rewrite the callback to return a bool indicating if it is okay to dismiss the modal.

**Review by dreacot — DISMISSED** [review]

**Review by Sirmorrison — APPROVED** [review]
LGTM
