### PR TITLE
Fixes account mixer bug

### LINKED ISSUE #686: Account Mixer toggle button bug
When the account mixer toggle button is clicked, a password modal pops up. if the cancel button is clicked, the toggle button should be set to off however, it is set to active.

ezgif com-gif-maker(12)

Also, if user decides the cancel the mixer action, a popup modal should be displayed asking the user to confirm the cancel action.

See example.
==
ezgif com-gif-maker(14)

### PR DESCRIPTION
**Pull request by AdimekweEbuka**
This PR fixes account mixer bug. Fixes #686 
godcr (testnet) 2021-11-03 00-465-00

Please note this PR also makes some changes in-order to avoid this (clicking outside the modal cancels the modal leaving the switch key still active):
fingodcr (testnet) 2021-11-03 00-46-00

**FIX**
godcr (testnet) 2021-11-12 05-43-14

### CODE REVIEW

**Review by devchoplife — COMMENTED** [review]
This looks and works fine on my end

File: ui/modal/password_modal.go [hunk 1]
```diff
@@ -45,7 +45,7 @@ func NewPasswordModal(l *load.Load) *PasswordModal {
 		modal:        *l.Theme.ModalFloatTitle(),
 		btnPositve:   l.Theme.Button("Confirm"),
 		btnNegative:  l.Theme.OutlineButton("Cancel"),
-		isCancelable: true,
```
Comment (Sirmorrison) [inline ui/modal/password_modal.go]: Revert this.

File: ui/modal/info_modal.go [hunk 2]
```diff
@@ -50,7 +50,7 @@ func NewInfoModal(l *load.Load) *InfoModal {
 		btnPositve:   l.Theme.OutlineButton("Yes"),
 		btnNegative:  l.Theme.OutlineButton("No"),
 		keyEvent:     l.Receiver.KeyEvents,
-		isCancelable: true,
+		isCancelable: false,
```
Comment (Sirmorrison) [inline ui/modal/info_modal.go]: Revert this.
due to this, the below modal cannot be minimized by clicking the background.
image

File: ui/modal/create_password_modal.go [hunk 3]
```diff
@@ -54,7 +54,7 @@ func NewCreatePasswordModal(l *load.Load) *CreatePasswordModal {
 		passwordStrength: l.Theme.ProgressBar(0),
 		btnPositve:       l.Theme.Button("Confirm"),
 		btnNegative:      l.Theme.OutlineButton("Cancel"),
-		isCancelable:     true,
+		isCancelable:     false,
```
Comment (Sirmorrison) [inline ui/modal/create_password_modal.go]: Revert this.

File: ui/page/wallets/privacy_page.go [hunk 4]
```diff
@@ -426,7 +426,18 @@ func (pg *PrivacyPage) showModalSetupMixerAcct() {
...
+				Title("Cancel mixer?").
+				Body("Are you sure you want to cancel mixer action?").
+				NegativeButton("No", func() {
+					pg.showModalPasswordStartAccountMixer()
+				}).
+				PositiveButton("Yes", func() {
+					pg.toggleMixer.SetChecked(false)
+				})
+			pg.ShowModal(info)
+		}).
```
Comment (Sirmorrison) [inline ui/page/wallets/privacy_page.go]:
```suggestion
		NegativeButton("Cancel", func() {
			pg.toggleMixer.SetChecked(false)
		}).
```
this is all you need as the mixing process has not started.

To set exit the info modal, you will need to add it here https://github.com/planetdecred/godcr/blob/977d09b6c16b4bd758b751c1e596e37aa0e4115f/ui/page/privacy_page.go#L347.

**Review by Sirmorrison — CHANGES_REQUESTED** [review]

**Comment by Sirmorrison** [comment]
Should you not want a modal to be canceled from the background, you can use the `SetCancelable(false)`

**Comment by dreacot** [comment]
Modals should be cancellable by clicking the backdrop, we already spent time creating a PR that solves that issue, we shouldn't be reverting it here

File: ui/modal/password_modal.go [hunk 5]
```diff
@@ -154,6 +154,7 @@ func (pm *PasswordModal) Handle() {
 	}
 
 	if pm.modal.BackdropClicked(pm.isCancelable) {
+		pm.negativeButtonClicked()
```
Comment (Sirmorrison) [inline ui/modal/password_modal.go]: This should be inside the condition.

**Review by Sirmorrison — CHANGES_REQUESTED** [review]

**Comment by AdimekweEbuka** [comment]
`in.negativeButtonClicked()` removed from info_modal (line 181). All info modals kept crashing the app when backdrop is clicked. Info modals working correctly now.

File: ui/modal/password_modal.go [hunk 6]
```diff
@@ -155,6 +155,7 @@ func (pm *PasswordModal) Handle() {
 
 	if pm.modal.BackdropClicked(pm.isCancelable) {
 		if !pm.isLoading {
+			pm.negativeButtonClicked()
```
Comment (Sirmorrison) [inline ui/modal/password_modal.go]: Kindly revert this as its not related to this PR.

Comment (Sirmorrison) [inline ui/modal/password_modal.go:158]: Kindly revert this as its not related to this PR.

**Review by Sirmorrison — CHANGES_REQUESTED** [review]

**Review by Sirmorrison — APPROVED** [review]
