### PR TITLE
Fix max button on send page

### LINKED ISSUE #393: max buttons on send page don't work
* The max button on the send page should fill up the amount field with the maximum amount of DCR that can be sent from the selected wallet account. Currently, nothing happens when the buttons are clicked
* The dollar equivalent field should be cleared when the DCR amount field is also cleared
* The DCR field should be modified when the amount in dollars is specified, currently only the value of the USD field is 
modified when the DCR amount is changed.
* Input field errors don't get cleared when I exit the send page.
* Account selector widget is currently showing the overall balance, It should instead be showing the spendable balance. This was fixed in PR #359 but was probably re-introduced in another PR

Screenshot 2021-04-29 at 15 55 52

### PR DESCRIPTION
**Pull request by tuhalang**
Resolves #393 
- Fill max amount when clicking the max button
- Clear the Dollar Equivalence field when the DCR Amount field is also cleared, and vice versa
- Clear input field error when exit send page
- Show the spendable balance in the account selector widget

### CODE REVIEW

**Comment by oshorefueled** [comment]
* I get a "not enough funds" error on the input field when I click the max button
* The USD field has the exact value as the DCR field when I use the max button. It should display the USD equivalent.
Screenshot 2021-05-01 at 18 34 26

File: ui/compontents.go [hunk 1]
```diff
@@ -466,13 +466,13 @@ func (page *pageCommon) accountSelectorLayout(gtx layout.Context, callingPage, s
 	case callingPage == "send":
 		acctName := page.info.Wallets[page.wallAcctSelector.selectedSendWallet].Accounts[page.wallAcctSelector.selectedSendAccount].Name
 		walName := page.info.Wallets[page.wallAcctSelector.selectedSendWallet].Name
-		bal := page.info.Wallets[page.wallAcctSelector.selectedSendWallet].Accounts[page.wallAcctSelector.selectedSendAccount].TotalBalance
-		return d(gtx, acctName, walName, bal, page.wallAcctSelector.sendAccountBtn)
+		bal := page.info.Wallets[page.wallAcctSelector.selectedSendWallet].Accounts[page.wallAcctSelector.selectedSendAccount].SpendableBalance
+		return d(gtx, acctName, walName, dcrutil.Amount(bal).String(), page.wallAcctSelector.sendAccountBtn)
```
Comment (oshorefueled) [inline ui/compontents.go]: set `page.info.Wallets[page.wallAcctSelector.selectedSendWallet]` to a variable to make the code line shorter and easier to read.

**Review by oshorefueled — CHANGES_REQUESTED** [review]

**Comment by oshorefueled** [comment]
I still get the "insufficient balance" bug when I use the max button. 

max_bug

**Comment by oshorefueled** [comment]
I'm currently experiencing this issue when using the button on different accounts

max_button_bug

**Comment by oshorefueled** [comment]
Clicking the max button take 2 or 3 seconds to populate the input field. And when I use the max button on an account with zero balance, it causes the entire window to freeze.

max_button

**Review by oshorefueled — APPROVED** [review]
