### PR TITLE
Fix entire license row not clickable on about page

### LINKED ISSUE #575: Entire license row on about page not clickable
On about page, the entire license row is not clickable. Only the text row is clickable. 
As seen below, the dark gray overlay is only present on the text row when clicked and other parts of the row are not clickable.
Screenshot from 2021-08-21 19-00-50

### PR DESCRIPTION
**Pull request by devchoplife**
This PR fixes #575 

It makes the whole license row on about page clickable:

Before:
Screenshot from 2021-08-21 19-00-50

After:
Screenshot from 2021-08-25 08-14-28

### CODE REVIEW

File: ui/page/about_page.go [hunk 1]
```diff
@@ -88,21 +88,62 @@ func (pg *AboutPage) Layout(gtx layout.Context) layout.Dimensions {
...
 		func(gtx C) D {
-			return components.EndToEndRow(gtx, pg.version.Layout, pg.versionValue.Layout)
+			return components.Container{
+				Padding: layout.Inset{
+					Top:    values.MarginPadding20,
+					Bottom: values.MarginPadding20,
+					Left:   values.MarginPadding16,
+					Right:  values.MarginPadding16,
+				},
+			}.Layout(gtx, func(gtx C) D {
```
Comment (Sirmorrison) [inline ui/page/about_page.go]: This can be added into a method and called for every instance where it is used/needed.

**Review by Sirmorrison — CHANGES_REQUESTED** [review]

File: ui/page/about_page.go [hunk 2]
```diff
@@ -85,24 +85,54 @@ func (pg *AboutPage) Layout(gtx layout.Context) layout.Dimensions {
...
+}
+
+func clickablePadding() layout.Inset {
+	return layout.Inset{
+		Top:    values.MarginPadding20,
+		Bottom: values.MarginPadding20,
+		Left:   values.MarginPadding16,
+		Right:  values.MarginPadding16,
+	}
+}
```
Comment (Sirmorrison) [inline ui/page/about_page.go]:
```suggestion
var inset = layout.Inset{
	Top:    values.MarginPadding20,
	Bottom: values.MarginPadding20,
	Left:   values.MarginPadding16,
	Right:  values.MarginPadding16,
}

func containerPadding() components.Container {
	return components.Container{
		Padding: inset,
	}
}

func padding() layout.Inset {
	return inset
}
```

**Review by Sirmorrison — CHANGES_REQUESTED** [review]

**Review by Sirmorrison — DISMISSED** [review]

File: ui/page/about_page.go [hunk 3]
```diff
@@ -85,24 +85,51 @@ func (pg *AboutPage) Layout(gtx layout.Context) layout.Dimensions {
...
+
+func containerPadding() components.Container {
+	return components.Container{
+		Padding: inset,
+	}
+}
+
+func padding() layout.Inset {
+	return inset
+}
```
Comment (oshorefueled) [inline ui/page/about_page.go]: Do you think we this? The Container type is like a syntactic sugar to differentiate the use of an inset for margin or padding. When using an Inset as a padding, use Container type and when using it as a margin, use the Inset type as it is. In this case, they do the same thing.

File: ui/page/about_page.go [hunk 4]
```diff
@@ -85,24 +85,51 @@ func (pg *AboutPage) Layout(gtx layout.Context) layout.Dimensions {
...
+
 func (pg *AboutPage) layoutRows(gtx layout.Context) layout.Dimensions {
 	w := []func(gtx C) D{
 		func(gtx C) D {
-			return components.EndToEndRow(gtx, pg.version.Layout, pg.versionValue.Layout)
+			return containerPadding().Layout(gtx, func(gtx C) D {
+				return components.EndToEndRow(gtx, pg.version.Layout, pg.versionValue.Layout)
+			})
```
Comment (oshorefueled) [inline ui/page/about_page.go]: Rather than create a method for container, you could use Container from the components package like so

```suggestion
			return components.Container{Padding: in}.Layout(gtx, func(gtx C) D {
				return components.EndToEndRow(gtx, pg.version.Layout, pg.versionValue.Layout)
			})
```

Where the variable `in` is a variable to the inset defined within the method `layoutRows()` as in
```go 
       in := layout.Inset{
		Top:    values.MarginPadding20,
		Bottom: values.MarginPadding20,
		Left:   values.MarginPadding16,
		Right:  values.MarginPadding16,
	}
```

File: ui/page/about_page.go [hunk 5]
```diff
@@ -85,24 +85,51 @@ func (pg *AboutPage) Layout(gtx layout.Context) layout.Dimensions {
...
+			return containerPadding().Layout(gtx, func(gtx C) D {
+				return components.EndToEndRow(gtx, pg.network.Layout, pg.networkValue.Layout)
+			})
 		},
 		func(gtx C) D {
 			return decredmaterial.Clickable(gtx, pg.licenseRow, func(gtx C) D {
 				return layout.Flex{}.Layout(gtx,
-					layout.Rigid(pg.license.Layout),
+					layout.Rigid(func(gtx C) D {
+						return padding().Layout(gtx, pg.license.Layout)
```
Comment (oshorefueled) [inline ui/page/about_page.go]: You could do the same thing here

**Review by oshorefueled — CHANGES_REQUESTED** [review]

**Review by Sirmorrison — DISMISSED** [review]

**Review by oshorefueled — APPROVED** [review]

File: ui/page/about_page.go [hunk 6]
```diff
@@ -85,24 +85,41 @@ func (pg *AboutPage) Layout(gtx layout.Context) layout.Dimensions {
 	return components.UniformPadding(gtx, body)
 }
 
+var in = layout.Inset{
+	Top:    values.MarginPadding20,
+	Bottom: values.MarginPadding20,
+	Left:   values.MarginPadding16,
+	Right:  values.MarginPadding16,
+}
+
```
Comment (oshorefueled) [inline ui/page/about_page.go]: The inset seems to only be used in the layoutRows method. You could make in a local variable in the method.

**Review by oshorefueled — CHANGES_REQUESTED** [review]

**Review by oshorefueled — APPROVED** [review]

**Review by Sirmorrison — APPROVED** [review]
