### PR TITLE
Fix newly created account and wallet ui display bug

### LINKED ISSUE #597: Newly created account not displaying on wallet page until manual reload
On the wallet page, when a new account is created under a particular wallet, or when account mixer is setup, the newly created accounts do not display on the UI until the application is restarted.

The expected behavior is to have the accounts display immediately they are created.

### LINKED ISSUE #607: Minimize modals
When the background of the modals are clicked, the modal should be minimized/closed.

ezgif com-gif-maker

### PR DESCRIPTION
**Pull request by Sirmorrison**
Fix #597
fix #607
This PR 
*updates create wallet modal to mock up ui.*
image
- it updates the colors on the password strength progress bar (weak, moderate, strong)
- it add an info message under the spend password editor
- update the button design to Mock up design
- update the modal button colors when all editors are empty or when an editor has input data

*it adds the create account modal*
image

- Fix bug with account not showing up on the ui after creation.
- Set maximum modal width to prevent modal from over stretching when app is in full screen and clean up modal widget
- Fix bug with progress bar filling up to 100% instead of progressing
- Fix bug with wallet list refresh after wallet is deleted or created
- Update info and password model button colors and styles to mock up design.
- Hide modal when backdrop/background is clicked.

### CODE REVIEW

File: ui/decredmaterial/modal.go [hunk 1]
```diff
@@ -10,6 +10,7 @@ import (
 
 type Modal struct {
 	overlayColor color.NRGBA
+	co           color.NRGBA
```
Comment (dreacot) [inline ui/decredmaterial/modal.go]: What is co? perhaps we can use a more descriptive name here

**Review by dreacot — DISMISSED** [review]

File: ui/modal/info_modal.go [hunk 2]
```diff
@@ -212,8 +223,6 @@ func (in *InfoModal) actionButtonsLayout() layout.Widget {
 					}
 
 					in.btnPositve.Text = in.positiveButtonText
-					in.btnPositve.Background, in.btnPositve.Color = in.Theme.Color.Surface, in.Theme.Color.Primary
```
Comment (beansgum) [inline ui/modal/info_modal.go:215]: A default background and color should be set so for pages without explicit positive button styles.

Screenshot 2021-09-14 at 10 21 32

File: ui/modal/create_watch_only_modal.go [hunk 3]
```diff
@@ -110,6 +110,11 @@ func (cm *CreateWatchOnlyModal) Handle() {
 			cm.Dismiss()
 		}
 	}
+
+	if cm.modal.BackdropClicked() {
```
Comment (beansgum) [inline ui/modal/create_watch_only_modal.go]: A check should be made before closing to avoid closing the modal while a process is running.

File: ui/modal/create_password_modal.go [hunk 4]
```diff
@@ -148,6 +159,11 @@ func (cm *CreatePasswordModal) Handle() {
 		}
 	}
 
+	if cm.modal.BackdropClicked() {
+		cm.Dismiss()
```
Comment (beansgum) [inline ui/modal/create_password_modal.go]: A check should be made before closing to avoid closing the modal while a process is running.

File: ui/modal/info_modal.go [hunk 5]
```diff
@@ -136,6 +142,11 @@ func (in *InfoModal) Handle() {
 		in.DismissModal(in)
 		in.negativeButtonClicked()
 	}
+
+	if in.modal.BackdropClicked() {
```
Comment (beansgum) [inline ui/modal/info_modal.go]: A `cancelable` property should be added for pages that do not want the modal to be canceled by tapping outside, some pages require a definite Yes or No.

File: ui/modal/create_watch_only_modal.go [hunk 6]
```diff
@@ -110,6 +110,11 @@ func (cm *CreateWatchOnlyModal) Handle() {
...
+		cm.Dismiss()
+		cm.RefreshWindow()
```
Comment (beansgum) [inline ui/modal/create_watch_only_modal.go]: This window refresh should be done here instead https://github.com/planetdecred/godcr/blob/master/ui/window.go#L207

File: ui/page/wallet_settings_page.go [hunk 7]
```diff
@@ -245,7 +245,7 @@ func (pg *WalletSettingsPage) Handle() {
 							}
 							pm.Dismiss()
 							pg.Toast.Notify("Wallet removed")
-							pg.PopFragment()
+							pg.ChangeFragment(NewWalletPage(pg.Load))
```
Comment (beansgum) [inline ui/page/wallet_settings_page.go]: This will be adding a new wallet page to the stack, PopFragment should be used to go back to the previous wallet page.

File: ui/page/wallet_page.go [hunk 8]
```diff
@@ -129,6 +129,10 @@ func (pg *WalletPage) ID() string {
 }
 
 func (pg *WalletPage) OnResume() {
+	pg.loadWalletAndAccounts()
+}
+
+func (pg *WalletPage) loadWalletAndAccounts() {
```
Comment (beansgum) [inline ui/page/wallet_page.go:138]: Should probably protect this with a mutex and instances where `pg.listItems` is accessed.

**Review by beansgum — CHANGES_REQUESTED** [review]

File: ui/modal/create_password_modal.go [hunk 9]
```diff
@@ -46,10 +49,14 @@ func NewCreatePasswordModal(l *load.Load) *CreatePasswordModal {
 		passwordStrength: l.Theme.ProgressBar(0),
 		btnPositve:       l.Theme.Button(new(widget.Clickable), "Confirm"),
 		btnNegative:      l.Theme.Button(new(widget.Clickable), "Cancel"),
+		isMinimizable:    true,
 	}
 
-	cm.btnPositve.TextSize, cm.btnNegative.TextSize = values.TextSize16, values.TextSize16
-	cm.btnPositve.Font.Weight, cm.btnNegative.Font.Weight = text.Bold, text.Bold
+	cm.btnNegative.TextSize = values.TextSize16
+	cm.btnNegative.Font.Weight = text.Bold
```
Comment (beansgum) [inline ui/modal/create_password_modal.go]: Use `text.Medium` for modal buttons according to the mockup.
```suggestion
	cm.btnNegative.Font.Weight = text.Medium
```

File: ui/modal/create_password_modal.go [hunk 10]
```diff
@@ -18,24 +19,26 @@ const CreateWallet = "create_wallet_modal"
...
+	modal                 decredmaterial.Modal
 	walletName            decredmaterial.Editor
 	passwordEditor        decredmaterial.Editor
 	confirmPasswordEditor decredmaterial.Editor
 	passwordStrength      decredmaterial.ProgressBarStyle
 
-	isLoading      bool
-	materialLoader material.LoaderStyle
+	isLoading         bool
+	isMinimizable     bool
```
Comment (beansgum) [inline ui/modal/create_password_modal.go]: The modal is actually being dismissed not minimized. 
```suggestion
	isCancelable     bool
```

File: ui/modal/create_password_modal.go [hunk 11]
```diff
@@ -184,7 +208,25 @@ func (cm *CreatePasswordModal) Layout(gtx layout.Context) D {
...
 		},
 		func(gtx C) D {
-			return cm.passwordEditor.Layout(gtx)
+			return layout.Flex{Axis: layout.Vertical}.Layout(gtx,
+				layout.Rigid(cm.passwordEditor.Layout),
+				layout.Rigid(func(gtx C) D {
+					return layout.Inset{Left: values.MarginPadding20, Right: values.MarginPadding20}.Layout(gtx, func(gtx C) D {
+						return layout.Flex{Spacing: layout.SpaceBetween}.Layout(gtx,
+							layout.Rigid(func(gtx C) D {
+								txt := cm.Theme.Label(values.MarginPadding14, "This spending password is for the new wallet only")
```
Comment (beansgum) [inline ui/modal/create_password_modal.go]: Why was this text added here? It's not included in the mockup and it shows up if I try to setup a startup password in settings.

File: ui/modal/create_watch_only_modal.go [hunk 12]
```diff
@@ -80,6 +84,10 @@ func (cm *CreateWatchOnlyModal) SetLoading(loading bool) {
 	cm.isLoading = loading
 }
 
+func (cm *CreateWatchOnlyModal) MinimizableBackground(min bool) {
```
Comment (beansgum) [inline ui/modal/create_watch_only_modal.go]: Can use `Cancelable(min bool)` or `SetCancelable` instead.

File: ui/modal/text_input_modal.go [hunk 13]
```diff
@@ -2,28 +2,34 @@ package modal
...
 )
 
 const TextInput = "text_input_modal"
 
 type TextInputModal struct {
 	*InfoModal
 
-	IsLoading bool
+	IsLoading     bool
+	ShowWarnInfo  bool
```
Comment (beansgum) [inline ui/modal/text_input_modal.go]: Should probably be specific since the info isn't customizable to any text. 
```suggestion
	ShowAccountWarnInfo  bool
```

File: ui/page/receive_page.go [hunk 14]
```diff
@@ -345,7 +345,7 @@ func (pg *ReceivePage) Handle() {
 		info := modal.NewInfoModal(pg.Load).
 			Title("Receive DCR").
 			Body("Each time you receive a payment, a new address is generated to protect your privacy.").
-			PositiveButton("Got it", func() {})
+			NegativeButton("Got it", func() {})
```
Comment (beansgum) [inline ui/page/receive_page.go]: Why is change done in multiple places?

**Review by beansgum — CHANGES_REQUESTED** [review]

File: ui/page/receive_page.go (hunk 14 above)
Comment (Sirmorrison) [reply ui/page/receive_page.go]: The `NegativeButton` is designed to minimize modals when no specific action is to be carried out.

File: ui/modal/create_password_modal.go (hunk 11 above)
Comment (Sirmorrison) [reply ui/modal/create_password_modal.go]: image
it is in the mock up..
i will fix the setting page.

**Review by dreacot — DISMISSED** [review]

File: ui/page/wallet_page.go [hunk 15]
```diff
@@ -410,6 +425,8 @@ func (pg *WalletPage) layoutOptionsMenu(gtx layout.Context, optionsMenuIndex int
 
 func (pg *WalletPage) walletSection(gtx layout.Context) layout.Dimensions {
 	return pg.walletsList.Layout(gtx, len(pg.listItems), func(gtx C, i int) D {
+		pg.listLock.Lock()
+		defer pg.listLock.Unlock()
```
Comment (beansgum) [inline ui/page/wallet_page.go]: Copy into a local variable, this defer could have unintended effects.
```suggestion
func (pg *WalletPage) walletSection(gtx layout.Context) layout.Dimensions {
	pg.listLock.Lock()
	listItems := pg.listItems
	pg.listLock.Unlock()
	return pg.walletsList.Layout(gtx, len(listItems), func(gtx C, i int) D {
```

File: ui/page/wallet_page.go [hunk 16]
```diff
@@ -534,6 +551,8 @@ func (pg *WalletPage) watchOnlyWalletSection(gtx layout.Context) layout.Dimensio
 
 func (pg *WalletPage) layoutWatchOnlyWallets(gtx layout.Context) D {
 	return pg.watchWalletsList.Layout(gtx, len(pg.listItems), func(gtx C, i int) D {
+		pg.listLock.Lock()
```
Comment (beansgum) [inline ui/page/wallet_page.go]: Copy into a local variable.

**Review by beansgum — CHANGES_REQUESTED** [review]

File: ui/page/wallet_page.go [hunk 17]
```diff
@@ -129,9 +132,16 @@ func (pg *WalletPage) ID() string {
...
 
 func (pg *WalletPage) OnResume() {
+	pg.loadWalletAndAccounts()
+}
+
+func (pg *WalletPage) loadWalletAndAccounts() {
 	wallets := pg.WL.SortedWalletList()
 
+	pg.listLock.Lock()
 	pg.listItems = make([]*walletListItem, 0)
```
Comment (beansgum) [inline ui/page/wallet_page.go]: Instead of doing this, store the `walletListItem` in a temp local slice and copy to locked slice when done.
```suggestion
	listItems := make([]*walletListItem, 0)
```

File: ui/page/wallet_page.go [hunk 18]
```diff
@@ -410,7 +425,11 @@ func (pg *WalletPage) layoutOptionsMenu(gtx layout.Context, optionsMenuIndex int
 
 func (pg *WalletPage) walletSection(gtx layout.Context) layout.Dimensions {
 	return pg.walletsList.Layout(gtx, len(pg.listItems), func(gtx C, i int) D {
+
+		pg.listLock.Lock()
 		listItem := pg.listItems[i]
+		pg.listLock.Unlock()
+
```
Comment (beansgum) [inline ui/page/wallet_page.go]: Put a local copy outside the loop to avoid access the mutex in every loop run.
```suggestion
func (pg *WalletPage) walletSection(gtx layout.Context) layout.Dimensions {
	pg.listLock.Lock()
	listItems := pg.listItems
	pg.listLock.Unlock()
	return pg.walletsList.Layout(gtx, len(listItems), func(gtx C, i int) D {

		listItem := pg.listItems[i]

```

File: ui/page/wallet_page.go [hunk 19]
```diff
@@ -534,7 +553,11 @@ func (pg *WalletPage) watchOnlyWalletSection(gtx layout.Context) layout.Dimensio
 
 func (pg *WalletPage) layoutWatchOnlyWallets(gtx layout.Context) D {
 	return pg.watchWalletsList.Layout(gtx, len(pg.listItems), func(gtx C, i int) D {
+
+		pg.listLock.Lock()
```
Comment (beansgum) [inline ui/page/wallet_page.go]: Put a local copy outside the loop to avoid access the mutex in every loop run.

**Review by beansgum — CHANGES_REQUESTED** [review]

File: ui/page/wallet_page.go [hunk 20]
```diff
@@ -169,9 +179,14 @@ func (pg *WalletPage) OnResume() {
...
 		}
-
-		pg.listItems = append(pg.listItems, listItem)
+		pg.listLock.Lock()
+		listItems = append(listItems, listItem)
+		pg.listLock.Unlock()
 	}
+
+	pg.listLock.Lock()
+	pg.listItems = append(pg.listItems, listItems...)
```
Comment (beansgum) [inline ui/page/wallet_page.go]: Is append the intended operation here?
```suggestion
	pg.listItems = listItems
```

File: ui/page/wallet_page.go [hunk 21]
```diff
@@ -169,9 +179,14 @@ func (pg *WalletPage) OnResume() {
 			listItem.backupAcctClickable = new(widget.Clickable)
 			listItem.collapsible = pg.Theme.CollapsibleWithOption()
 		}
-
-		pg.listItems = append(pg.listItems, listItem)
+		pg.listLock.Lock()
```
Comment (beansgum) [inline ui/page/wallet_page.go]: Lock not needed to write to local copy

File: ui/page/wallet_page.go [hunk 22]
```diff
@@ -129,9 +132,16 @@ func (pg *WalletPage) ID() string {
...
 
 func (pg *WalletPage) OnResume() {
+	pg.loadWalletAndAccounts()
+}
+
+func (pg *WalletPage) loadWalletAndAccounts() {
 	wallets := pg.WL.SortedWalletList()
 
-	pg.listItems = make([]*walletListItem, 0)
+	pg.listLock.Lock()
```
Comment (beansgum) [inline ui/page/wallet_page.go]: Lock is not needed here.

**Review by beansgum — CHANGES_REQUESTED** [review]

File: ui/page/wallet_page.go [hunk 23]
```diff
@@ -409,8 +424,14 @@ func (pg *WalletPage) layoutOptionsMenu(gtx layout.Context, optionsMenuIndex int
...
 
 func (pg *WalletPage) walletSection(gtx layout.Context) layout.Dimensions {
-	return pg.walletsList.Layout(gtx, len(pg.listItems), func(gtx C, i int) D {
+	pg.listLock.Lock()
+	listItems := pg.listItems
+	pg.listLock.Unlock()
+
+	return pg.walletsList.Layout(gtx, len(listItems), func(gtx C, i int) D {
+
 		listItem := pg.listItems[i]
```
Comment (beansgum) [inline ui/page/wallet_page.go]:
```suggestion
		listItem := listItems[i]
```

**Review by beansgum — CHANGES_REQUESTED** [review]
There're some usages of listItems that are not protected by mutex:
https://github.com/planetdecred/godcr/blob/339cdd9bb043cdbe6feb4b8778e022d645f72d56/ui/page/wallet_page.go#L465
https://github.com/planetdecred/godcr/blob/339cdd9bb043cdbe6feb4b8778e022d645f72d56/ui/page/wallet_page.go#L524
https://github.com/planetdecred/godcr/blob/339cdd9bb043cdbe6feb4b8778e022d645f72d56/ui/page/wallet_page.go#L563
https://github.com/planetdecred/godcr/blob/339cdd9bb043cdbe6feb4b8778e022d645f72d56/ui/page/wallet_page.go#L599
https://github.com/planetdecred/godcr/blob/339cdd9bb043cdbe6feb4b8778e022d645f72d56/ui/page/wallet_page.go#L855

File: ui/page/wallet_page.go [hunk 24]
```diff
@@ -441,7 +462,10 @@ func (pg *WalletPage) walletSection(gtx layout.Context) layout.Dimensions {
 						})
 					}),
 					layout.Rigid(func(gtx C) D {
-						return decredmaterial.Clickable(gtx, pg.listItems[i].addAcctClickable, func(gtx C) D {
+						pg.listLock.Lock()
+						listItem := pg.listItems[i]
+						pg.listLock.Unlock()
```
Comment (beansgum) [inline ui/page/wallet_page.go]: You can use the list item declared earlier here https://github.com/planetdecred/godcr/blob/09cabbcfc0037772251c4648f00dfcf412d6dd81/ui/page/wallet_page.go#L433

File: ui/page/wallet_page.go [hunk 25]
```diff
@@ -568,8 +603,11 @@ func (pg *WalletPage) layoutWatchOnlyWallets(gtx layout.Context) D {
 					)
 				}),
 				layout.Rigid(func(gtx C) D {
+					pg.listLock.Lock()
+					listItems := pg.listItems
+					pg.listLock.Unlock()
```
Comment (beansgum) [inline ui/page/wallet_page.go]: Use the listItems declared earlier https://github.com/planetdecred/godcr/blob/09cabbcfc0037772251c4648f00dfcf412d6dd81/ui/page/wallet_page.go#L566

**Review by beansgum — CHANGES_REQUESTED** [review]

**Review by beansgum — APPROVED** [review]

**Review by dreacot — APPROVED** [review]
