### PR TITLE
fix governance click bug

### LINKED ISSUE #997: buttons don't respond to click events on the governance page
since the app package was implemented, buttons on the governance sub pages(Proposals, Consensus), no longer respond to click events.

### PR DESCRIPTION
**Pull request by Sirmorrison**
fix #997 

Previously, the user interaction on the governance sub pages were not being handled by the master page(Governance page), so all click events were ignored. The solution was to initialize the `HandleUserInteractions()` method of the sub pages from the governance page.

Fix app crash when the reject dropdown option is selected. This was as a result of integer from the error. 0/0 = infinity converting this to floating points

### CODE REVIEW

File: ui/page/components/votebar_widget.go [hunk 1]
```diff
@@ -260,12 +260,13 @@ func (v *VoteBar) layoutIconAndText(gtx C, lbl decredmaterial.Label, count int,
 				return lbl.Layout(gtx)
 			}),
 			layout.Rigid(func(gtx C) D {
-				percentage := (count / v.totalVotes) * 100
+				count := float64(count)
+				percentage := (count / float64(v.totalVotes)) * 100
 				if percentage < 0 {
```
Comment (itswisdomagain) [inline ui/page/components/votebar_widget.go:265]: Can `count` or `v.totalVotes` be less than 0? If that's not possible, this check is useless.

**Review by itswisdomagain — APPROVED** [review]

**Comment by itswisdomagain** [comment]
Not sure what was causing `app crash when the reject dropdown option is selected`, based on the changes in this PR. Can you call that out?

File: ui/page/components/votebar_widget.go (hunk 1 above)
Comment (Sirmorrison) [reply ui/page/components/votebar_widget.go:265]: I think when implementing this earlier, we ran into this issue hence the check.

**Comment by Sirmorrison** [comment]
> Not sure what was causing `app crash when the reject dropdown option is selected`, based on the changes in this PR. Can you call that out?

yeah.. the was as a result of integer from the error. `0/0 = infinity` converting this to floating points, resolved the issue.

File: ui/page/components/votebar_widget.go (hunk 1 above)
Comment (itswisdomagain) [reply ui/page/components/votebar_widget.go:265]: Weird, but okay. I think it'd be good to log if either count or v.totalVotes were negative.

**Comment by itswisdomagain** [comment]
> result of integer from the error. `0/0 = infinity`

should ideally NOT do a division if the denominator is 0

**Comment by dreacot** [comment]
`Fix app crash when the reject dropdown option is selected`. can you update the PR description on what the cause of the crash is, and what the solution is

**Comment by Sirmorrison** [comment]
> `Fix app crash when the reject dropdown option is selected`. can you update the PR description on what the cause of the crash is, and what the solution is

Done

**Review by dreacot — DISMISSED** [review]

File: ui/page/components/votebar_widget.go (hunk 1 above)
Comment (dreacot) [reply ui/page/components/votebar_widget.go:265]: @Sirmorrison are we going to be logging the output in this PR?

Comment (Sirmorrison) [reply ui/page/components/votebar_widget.go:265]: No need logging it as i dont see the use.

**Review by dreacot — APPROVED** [review]
