### PR TITLE
Max amount button bugs on Send  page

### LINKED ISSUE #732: Send page Max amount button bug
currently, on the send page, when the Max amount button is clicked, the editor is supposed to be populated with the maximum wallet amount. However, when the button is clicked, nothing happens until you switch to my address and back.

Also, If the amount is highlighted and cleared, the max amount button is not reset.
ezgif com-gif-maker

### PR DESCRIPTION
**Pull request by devchoplife**
Closes #732 

The address should be validated first before the amount is set 
Within the constructTx() function, unsignedTx is required to calculate the tx fee which will be deducted from the total number of coins 
One of the arguments of unsignedTx.addSenddestination is destination address 

In the light of this, this PR

- Adds toast notification "Set destination address" if max button is clicked and amount is not set 
- Fixes rhe bug that keeps the max button active when amount input is highlighted and cleared

### CODE REVIEW

File: ui/page/send/send_amount.go [hunk 1]
```diff
@@ -21,9 +21,9 @@ type sendAmount struct {
 	dcrAmountEditor decredmaterial.Editor
 	usdAmountEditor decredmaterial.Editor
 
-	sendMax               bool
-	dcrSendMaxChangeEvent bool
-	usdSendMaxChangeEvent bool
+	Sendmax               bool
```
Comment (dreacot) [inline ui/page/send/send_amount.go:24]:
```suggestion
	SendMax               bool
```
replace all instances

File: ui/page/send/send_amount.go [hunk 2]
```diff
@@ -69,34 +69,34 @@ func (sa *sendAmount) setExchangeRate(exchangeRate float64) {
 func (sa *sendAmount) setAmount(amount int64) {
 	// TODO: this workaround ignores the change events from the
 	// amount input to avoid construct tx cycle.
-	sa.dcrSendMaxChangeEvent = sa.sendMax
+	sa.dcrSendmaxChangeEvent = sa.Sendmax
```
Comment (dreacot) [inline ui/page/send/send_amount.go:72]:
```suggestion
	sa.dcrSendMaxChangeEvent = sa.SendMax
```

File: ui/page/send/send_amount.go [hunk 3]
```diff
@@ -69,34 +69,34 @@ func (sa *sendAmount) setExchangeRate(exchangeRate float64) {
...
 	sa.dcrAmountEditor.Editor.SetText(fmt.Sprintf("%.8f", dcrutil.Amount(amount).ToCoin()))
 
 	if sa.exchangeRate != -1 {
 		usdAmount := load.DCRToUSD(sa.exchangeRate, dcrutil.Amount(amount).ToCoin())
 
-		sa.usdSendMaxChangeEvent = true
+		sa.usdSendmaxChangeEvent = true
```
Comment (dreacot) [inline ui/page/send/send_amount.go:78]:
```suggestion
		sa.usdSendMaxChangeEvent = true
```

**Review by dreacot — APPROVED** [review]

File: ui/page/send/send_amount.go (hunk 1 above)
Comment (dreacot) [inline ui/page/send/send_amount.go]:
```suggestion
	SendMax               bool
```
replace all instances

File: ui/page/send/send_amount.go [hunk 4]
```diff
@@ -21,9 +21,9 @@ type sendAmount struct {
 	dcrAmountEditor decredmaterial.Editor
 	usdAmountEditor decredmaterial.Editor
 
-	sendMax               bool
-	dcrSendMaxChangeEvent bool
-	usdSendMaxChangeEvent bool
+	Sendmax               bool
+	dcrSendmaxChangeEvent bool
```
Comment (dreacot) [inline ui/page/send/send_amount.go]:
```suggestion
	dcrSendMaxChangeEvent bool
```

File: ui/page/send/send_amount.go [hunk 5]
```diff
@@ -21,9 +21,9 @@ type sendAmount struct {
...
+	usdSendmaxChangeEvent bool
```
Comment (dreacot) [inline ui/page/send/send_amount.go]:
```suggestion
	usdSendMaxChangeEvent bool
```

**Review by dreacot — CHANGES_REQUESTED** [review]

**Review by dreacot — CHANGES_REQUESTED** [review]
The error message should say "set destination address"

Screenshot 2021-12-31 at 8 37 38 AM

**Comment by dreacot** [comment]
based on the original issue, sometimes when the dcr amount editor is highlighted and cleared, the max button is not reset, same goes for the usd amount editor

**Comment by dreacot** [comment]
the corresponding amount editor field should be cleared when one amount editor field is clear
Screenshot 2021-12-31 at 6 45 14 PM

**Review by dreacot — APPROVED** [review]
