### PR TITLE
restore default subpage icon

### LINKED ISSUE #477: navigating to the receive page changes the return button on all sub pages
Navigating to the receive page changes return button icons on all sub pages from the left arrow icon to the cancel icon. 

#### To reproduce:
* Navigate to the "more" page
* Open the settings page
Screenshot 2021-06-18 at 14 57 57

* From the settings page, navigate to the receive page
On closing the receive page and going back to the settings page, it will be observed that the return/back button icon changes to the cancel icon. 

Screenshot 2021-06-18 at 14 59 40

### PR DESCRIPTION
**Pull request by Sirmorrison**
Fix #477
The pr restores the default subpage icon after navigating to either the receive page or the send page.

### CODE REVIEW

File: ui/receive_page.go [hunk 1]
```diff
@@ -329,6 +329,7 @@ func (pg *receivePage) handle() {
 
 	if common.subPageBackButton.Button.Clicked() {
 		common.changePage(*common.returnPage)
+		common.subPageBackButton.Icon = common.icons.navigationArrowBack
```
Comment (oshorefueled) [inline ui/receive_page.go]: This looks like it should be in the onClose() method for the receive page. Same as the send page.

**Review by oshorefueled — CHANGES_REQUESTED** [review]

**Comment by oshorefueled** [comment]
I can't go back from the transactions detail page after navigating to the receive page.
To Reproduce
* go to a transaction detail page
* navigate to the receive page
* close the receive page

Trying to click the back button on the transaction detail page doesn't work.

**Review by oshorefueled — APPROVED** [review]
