### PR TITLE
Fix navigation when click the cancel button on the send and receive page

### LINKED ISSUE #390: cancel button on send and receive page always navigates to the overview page
When I click on the cancel button on the send and receive page, I should be navigated back to the previous page not the overview page. The send and receive pages need a state of the previous page which will be navigated to when the cancel button is clicked.

### PR DESCRIPTION
**Pull request by tuhalang**
Resolves #390 
- Currently, when clicking on the cancel button on the send and receive page, it always navigates to the overview page. This modifies the cancel button navigation to return to the previous page.

### CODE REVIEW

File: ui/receive_page.go [hunk 1]
```diff
@@ -331,7 +331,7 @@ func (pg *receivePage) Handle(common pageCommon) {
 	}
 
 	if common.subPageBackButton.Button.Clicked() {
-		*common.page = PageOverview
+		*common.page = *common.returnPage
```
Comment (oshorefueled) [inline ui/receive_page.go]: the changePage method should be used rather than a direct assignment.

**Review by oshorefueled — CHANGES_REQUESTED** [review]

**Review by oshorefueled — APPROVED** [review]
