### PR TITLE
Disable receive, send and mixer navigation option for watch only wallet.

### LINKED ISSUE #1050: crash when clicking send page, during sync
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x120cadb]

goroutine 16 [running]:
github.com/planetdecred/godcr/ui/page/components.(*AccountSelector).Layout.func2({{{0x0, 0x0}, {0x1d8, 0xf41cb}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/components/account_selector.go:157 +0x3b
gioui.org/layout.Flex.Layout({0xc3, 0x0, 0x0, 0x0}, {{{0x0, 0x0}, {0x1f8, 0xf41cb}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/flex.go:99 +0xdb5
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2.1.1.1({{{0x0, 0x0}, {0x1f8, 0xf41cb}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:89 +0x85
gioui.org/layout.Direction.Layout(0x0, {{{0x0, 0x0}, {0x1f8, 0xf41cb}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, ...}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:166 +0x162
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2.1.1({{{0x1f8, 0x0}, {0x1f8, 0xf41cb}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:88 +0xe5
gioui.org/layout.Inset.Layout({0x852, 0x0, 0x0, 0x0}, {{{0x1f8, 0x0}, {0x1f8, 0xf41cb}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:139 +0x3b6
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2.1({{{0x210, 0x0}, {0x210, 0xf41e3}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:86 +0x109
github.com/planetdecred/godcr/ui/decredmaterial.Border.Layout({{0x3d, 0x3d, 0x3d, 0xff}, {0x8, 0x8, 0x8, 0x8}, 0x40000000}, {{{0x210, ...}, ...}, ...}, ...)
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/border.go:21 +0x98
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2({{{0x210, 0x0}, {0x210, 0xf41e3}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:84 +0x1d6
gioui.org/layout.Stack.Layout({0x0}, {{{0x0, 0x0}, {0x210, 0xf41e3}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, ...}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/stack.go:60 +0x8b6
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1({{{0x0, 0x0}, {0x210, 0xf41e3}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:47 +0x2aa
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1({{{0x0, 0x0}, {0x210, 0xf41e3}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:108 +0x238
gioui.org/layout.Inset.Layout({0x48b8, 0x0, 0x0, 0x0}, {{{0x0, 0x0}, {0x210, 0xf41e3}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:139 +0x3b6
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1({{{0x0, 0x0}, {0x210, 0xf41e3}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:44 +0x109
gioui.org/layout.Direction.Layout(0x0, {{{0x0, 0x0}, {0x210, 0xf41e3}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, ...}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:166 +0x162
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout({0xfffffffffffffffe, 0xffffffffffffffff, 0x0, {0x0, 0x0, 0x0, 0x0}, 0x0, {{0x3d, 0x3d, ...}, ...}, ...}, ...)
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:42 +0xe5
github.com/planetdecred/godcr/ui/page/components.(*AccountSelector).Layout(0xc00d916900, {0x1de6580, 0xc00077dda0}, {{{0x0, 0x0}, {0x210, 0xf41e3}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/components/account_selector.go:146 +0x3e5
github.com/planetdecred/godcr/ui/page/send.(*Page).layoutDesktop.func1.1({{{0x0, 0x0}, {0x210, 0xf41e3}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/send/layout.go:159 +0x87
gioui.org/layout.Flex.Layout({0x0, 0x0, 0x0, 0x0}, {{{0x0, 0x0}, {0x210, 0xf4208}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/flex.go:99 +0xdb5
github.com/planetdecred/godcr/ui/page/send.(*Page).pageSections.func1.1({{{0x0, 0x0}, {0x210, 0xf4208}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/send/layout.go:277 +0x1f8
gioui.org/layout.Inset.Layout({0xbc, 0x0, 0xbb, 0x0}, {{{0x0, 0x0}, {0x210, 0xf4208}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:139 +0x3b6
github.com/planetdecred/godcr/ui/page/send.(*Page).pageSections.func1({{{0x0, 0x0}, {0x230, 0xf4228}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/send/layout.go:276 +0xca
gioui.org/layout.Stack.Layout({0x94}, {{{0x230, 0x0}, {0x230, 0xf4228}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, ...}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/stack.go:60 +0x8b6
github.com/planetdecred/godcr/ui/decredmaterial.Card.Layout.func1({{{0x230, 0x0}, {0x230, 0xf4228}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/card.go:64 +0x18e
gioui.org/layout.Inset.Layout({0x30, 0x0, 0x30, 0x0}, {{{0x230, 0x0}, {0x230, 0xf4228}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:139 +0x3b6
github.com/planetdecred/godcr/ui/decredmaterial.Card.Layout({{0x0, 0x0, 0x0, 0x0}, {0x25, 0x25, 0x25, 0xff}, {0x12, 0x12, ...}, ...}, ...)
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/card.go:63 +0x129
github.com/planetdecred/godcr/ui/page/send.(*Page).pageSections(0xc00336c000, {{{0x230, 0x0}, {0x230, 0xf4228}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, ...}, ...}, ...)
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/send/layout.go:275 +0x218
github.com/planetdecred/godcr/ui/page/send.(*Page).layoutDesktop.func1({{{0x230, 0x0}, {0x230, 0xf4228}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/send/layout.go:158 +0xd2
gioui.org/layout.Inset.Layout({0xbb, 0x0, 0xbc, 0x0}, {{{0x230, 0x0}, {0x230, 0xf4228}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:139 +0x3b6
github.com/planetdecred/godcr/ui/page/send.(*Page).layoutDesktop.func4.1.1.2.1.1({{{0x230, 0x0}, {0x230, 0xf4230}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/send/layout.go:183 +0x6b
gioui.org/layout.Inset.Layout({0xba, 0x0, 0x4778, 0x0}, {{{0x230, 0x0}, {0x230, 0xf4230}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:139 +0x3b6
github.com/planetdecred/godcr/ui/page/send.(*Page).layoutDesktop.func4.1.1.2.1({{{0x232, 0x0}, {0x232, 0xf4240}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...}, ...)
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/send/layout.go:182 +0xc6
gioui.org/layout.(*List).Layout(0xc00decd550, {{{0x232, 0x0}, {0x232, 0xf4240}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, ...}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/list.go:117 +0x17c
gioui.org/widget/material.ListStyle.Layout({0xc00decd500, {0xc00decd500, {0x40000000, 0x40000000, {0x0, 0x0, 0x0, 0x0}}, {0x41000000, 0x40c00000, ...}}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/widget/material/list.go:269 +0x20c
github.com/planetdecred/godcr/ui/decredmaterial.ListStyle.Layout(...)
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/list_scroll.go:39
github.com/planetdecred/godcr/ui/page/send.(*Page).layoutDesktop.func4.1.1.2({{{0x0, 0x0}, {0x23c, 0x1cd}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/send/layout.go:181 +0x1c5
gioui.org/layout.Flex.Layout({0x0, 0x0, 0x0, 0x0}, {{{0x0, 0x0}, {0x23c, 0x1fd}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/flex.go:99 +0xdb5
github.com/planetdecred/godcr/ui/page/send.(*Page).layoutDesktop.func4.1.1({{{0x0, 0x0}, {0x23c, 0x1fd}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/send/layout.go:174 +0x218
gioui.org/layout.Inset.Layout({0x12fa37d, 0x0, 0x0, 0x0}, {{{0x0, 0x0}, {0x23c, 0x1fd}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:139 +0x3b6
github.com/planetdecred/godcr/ui/page/components.UniformPadding({{{0x0, 0x0}, {0x26c, 0x22d}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...}, ...)
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/components/components.go:92 +0x197
github.com/planetdecred/godcr/ui/page/send.(*Page).layoutDesktop.func4.1({{{0x0, 0x0}, {0x26c, 0x22d}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/send/layout.go:173 +0xbd
gioui.org/layout.Stack.Layout({0xf0}, {{{0x26c, 0x22d}, {0x26c, 0x22d}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, ...}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/stack.go:78 +0x5dc
github.com/planetdecred/godcr/ui/page/send.(*Page).layoutDesktop.func4({{{0x26c, 0x22d}, {0x26c, 0x22d}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/send/layout.go:171 +0x18e
gioui.org/layout.Stack.Layout({0x0}, {{{0x0, 0x0}, {0x26c, 0x22d}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, ...}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/stack.go:78 +0x5dc
github.com/planetdecred/godcr/ui/page/send.(*Page).layoutDesktop(0xc00336c000, {{{0x0, 0x0}, {0x26c, 0x22d}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/send/layout.go:169 +0x3b4
github.com/planetdecred/godcr/ui/page/send.(*Page).Layout(0xc00336c000, {{{0x0, 0x0}, {0x26c, 0x22d}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/send/layout.go:152 +0x105
github.com/planetdecred/godcr/ui/page.(*MainPage).layoutDesktop.func1.1.1({{{0x0, 0x0}, {0x26c, 0x22d}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/main_page.go:667 +0x7d
gioui.org/layout.Flex.Layout({0x2a, 0x0, 0x0, 0x0}, {{{0x0, 0x0}, {0x320, 0x22d}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/flex.go:99 +0xdb5
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2.1.1.1({{{0x0, 0x0}, {0x320, 0x22d}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:89 +0x85
gioui.org/layout.Direction.Layout(0x0, {{{0x0, 0x0}, {0x320, 0x22d}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, ...}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:166 +0x162
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2.1.1({{{0x320, 0x22d}, {0x320, 0x22d}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:88 +0xe5
gioui.org/layout.Inset.Layout({0x26a120, 0xc0, 0x0, 0x0}, {{{0x320, 0x22d}, {0x320, 0x22d}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:139 +0x3b6
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2.1({{{0x320, 0x22d}, {0x320, 0x22d}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:86 +0x109
github.com/planetdecred/godcr/ui/decredmaterial.Border.Layout({{0x0, 0x0, 0x0, 0x0}, {0x0, 0x0, 0x0, 0x0}, 0x0}, {{{0x320, ...}, ...}, ...}, ...)
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/border.go:21 +0x98
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2({{{0x320, 0x22d}, {0x320, 0x22d}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:84 +0x1d6
gioui.org/layout.Stack.Layout({0xd0}, {{{0x0, 0x0}, {0x320, 0x22d}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, ...}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/stack.go:60 +0x8b6
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1({{{0x0, 0x0}, {0x320, 0x22d}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:47 +0x2aa
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1({{{0x0, 0x0}, {0x320, 0x22d}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:108 +0x238
gioui.org/layout.Inset.Layout({0x2298e8, 0xc0, 0x24ce59a0, 0xc0ba61e5}, {{{0x0, 0x0}, {0x320, 0x22d}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:139 +0x3b6
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1({{{0x0, 0x0}, {0x320, 0x22d}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:44 +0x109
gioui.org/layout.Direction.Layout(0x0, {{{0x0, 0x0}, {0x320, 0x22d}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, ...}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:166 +0x162
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout({0xfffffffffffffffe, 0xfffffffffffffffe, 0x0, {0x0, 0x0, 0x0, 0x0}, 0x0, {{0x0, 0x0, ...}, ...}, ...}, ...)
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:42 +0xe5
github.com/planetdecred/godcr/ui/page.(*MainPage).layoutDesktop.func1.1({{{0x0, 0x0}, {0x320, 0x22d}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/main_page.go:661 +0x205
gioui.org/layout.Flex.Layout({0x5, 0x0, 0x0, 0x0}, {{{0x0, 0x0}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/flex.go:99 +0xdb5
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2.1.1.1({{{0x0, 0x0}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:89 +0x85
gioui.org/layout.Direction.Layout(0x0, {{{0x0, 0x0}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, ...}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:166 +0x162
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2.1.1({{{0x320, 0x258}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:88 +0xe5
gioui.org/layout.Inset.Layout({0x5d1ae8, 0xc0, 0xf6f9dd, 0x0}, {{{0x320, 0x258}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:139 +0x3b6
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2.1({{{0x320, 0x258}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:86 +0x109
github.com/planetdecred/godcr/ui/decredmaterial.Border.Layout({{0x0, 0x0, 0x0, 0x0}, {0x0, 0x0, 0x0, 0x0}, 0x0}, {{{0x320, ...}, ...}, ...}, ...)
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/border.go:21 +0x98
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2({{{0x320, 0x258}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:84 +0x1d6
gioui.org/layout.Stack.Layout({0x0}, {{{0x0, 0x0}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, ...}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/stack.go:60 +0x8b6
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1({{{0x0, 0x0}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:47 +0x2aa
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1({{{0x0, 0x0}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:108 +0x238
gioui.org/layout.Inset.Layout({0x475ae7, 0x0, 0xf5314c, 0x0}, {{{0x0, 0x0}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:139 +0x3b6
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1({{{0x0, 0x0}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:44 +0x109
gioui.org/layout.Direction.Layout(0x0, {{{0x0, 0x0}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, ...}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:166 +0x162
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout({0xfffffffffffffffe, 0xfffffffffffffffe, 0x1, {0x0, 0x0, 0x0, 0x0}, 0x0, {{0x0, 0x0, ...}, ...}, ...}, ...)
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/decredmaterial/linearlayout.go:42 +0xe5
github.com/planetdecred/godcr/ui/page.(*MainPage).layoutDesktop.func1({{{0x0, 0x0}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/main_page.go:654 +0x20b
gioui.org/layout.Stack.Layout({0x90}, {{{0x0, 0x0}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, ...}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/stack.go:78 +0x5dc
github.com/planetdecred/godcr/ui/page.(*MainPage).layoutDesktop(0xc0059b9200, {{{0x0, 0x0}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/main_page.go:648 +0x12b
github.com/planetdecred/godcr/ui/page.(*MainPage).Layout(0xc0059b9200, {{{0x0, 0x0}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/page/main_page.go:644 +0x105
github.com/planetdecred/godcr/ui.(*Window).prepareToDisplayUI.func2({{{0x0, 0x0}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, 0x3d519d211d, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/window.go:226 +0xd9
gioui.org/layout.Stack.Layout({0x20}, {{{0x320, 0x258}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1d95ec0, 0xc0002298e8}, {0xc0ba61e524ce59a0, ...}, ...}, ...)
        /home/kennedy/Projects/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/stack.go:60 +0x8b6
github.com/planetdecred/godcr/ui.(*Window).prepareToDisplayUI(0xc00020bd60, {{0xc0ba61e524ce59a0, 0x3d519d211d, 0x2efa300}, {0x3f800000, 0x3f800000}, {0x320, 0x258}, {0x0, 0x0, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/window.go:241 +0x42d
github.com/planetdecred/godcr/ui.(*Window).handleFrameEvent(0xc00020bd60, {{0xc0ba61e524ce59a0, 0x3d519d211d, 0x2efa300}, {0x3f800000, 0x3f800000}, {0x320, 0x258}, {0x0, 0x0, ...}, ...})
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/window.go:182 +0x227
github.com/planetdecred/godcr/ui.(*Window).HandleEvents(0xc00020bd60)
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/ui/window.go:148 +0x156
main.main.func2()
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/main.go:80 +0x26
created by main.main
        /home/kennedy/Projects/src/github.com/planetdecred/godcr/main.go:79 +0x4d2
exit status 2
```

### PR DESCRIPTION
**Pull request by Sirmorrison**
Fix #1050 

This Pr disables the send, receive, and stakeshuffle navigation option for watch only wallets. it also disables create account settings button.

watch only wallets as the name implies are for watching only and do not send or receive funds. Also since they dont send and receive funds, they cannot create new account or mix funds well.

image

### CODE REVIEW

**Review by devchoplife — COMMENTED** [review]
LGTM

File: ui/page/wallet_settings_page.go [hunk 1]
```diff
@@ -282,7 +282,11 @@ func (pg *WalletSettingsPage) pageSections(gtx C, title string, body layout.Widg
 							}
 							if title == values.String(values.StrAccount) {
 								return layout.E.Layout(gtx, func(gtx C) D {
-									return pg.addAccount.Layout(gtx, pg.Theme.Icons.AddIcon.Layout24dp)
+									mGtx := gtx
+									if pg.WL.SelectedWallet.Wallet.IsWatchingOnlyWallet() {
```
Comment (JustinBeBoy) [inline ui/page/wallet_settings_page.go:286]: I don't think we need to disable it, we should hide it

**Review by JustinBeBoy — DISMISSED** [review]

**Comment by JustinBeBoy** [comment]
1. I don't think we need to disable receive, send, mixer navigation option and add account button in wallet setting page, we should hide it
2. The spending password, spend unconfirmed funds and allow spending from unmixed account not need with watch wallet, so those options need to be hidden in wallet setting page

**Comment by Sirmorrison** [comment]
> 1. I don't think we need to disable receive, send, mixer navigation option and add account button in wallet setting page, we should hide it
> 
>     2. The spending password, spend unconfirmed funds and allow spending from unmixed account not need with watch wallet, so those options need to be hidden in wallet setting page

Hiding the option would be a decision for later with a UI update... the aim is to fix the crash related bug. 

Also, the settings option mentioned does not have any impact on the app as they are config values and setting them would still not affect the app as the config would not take effect, since we are only watching and not making transactions.

**Comment by dreacot** [comment]
I agree with Justindo, if we aren't going to display an info as to why those entries are disabled, we might as well hide them

**Review by dreacot — APPROVED** [review]
Merging as is, till the updated product design is provided
