### PR TITLE
Fix seed editor bugs

### LINKED ISSUE #828: Wallet restore seed validation bug
On the Wallet page, when you try import a new wallet, an `invalid seed phrase` error is displayed just when you start typing the last seed.

Allow validation to start only after the last seed phrase has been entered.

image

### PR DESCRIPTION
**Pull request by devchoplife**
Resolves #828 
This PR fixes the bugs listed below:
-  invalid suggestions showing up on some seed editors when navigated to.
- ` ìnvaid seed phrase ` error showing up before user has finished entering their seed phrase 

This PR also implements:
- Filling the seed editor with the first suggestion instead of the only suggestion 
- Setting the selected menu item to the first item when the seed editor is changed

### CODE REVIEW

**Review by Sirmorrison — CHANGES_REQUESTED** [review]
i get this error about empty seeds.
image
This was reproduced a couple of times.

Then this 
image

File: ui/page/wallets/restore_page.go [hunk 1]
```diff
@@ -493,12 +509,17 @@ func (pg *Restore) HandleUserInteractions() {
 	select {
 	case evt := <-pg.keyEvent:
 		if evt.Name == key.NameTab && evt.State == key.Press {
-			if len(pg.suggestions) == 1 {
-				focus := pg.seedEditors.focusIndex
-				pg.seedEditors.editors[focus].Edit.Editor.SetText(pg.suggestions[0])
-				pg.seedClicked = true
-				pg.seedEditors.editors[focus].Edit.Editor.MoveCaret(len(pg.suggestions[0]), -1)
+			focus := pg.seedEditors.focusIndex
```
Comment (Sirmorrison) [inline ui/page/wallets/restore_page.go]: This should go into the `if` statement.

File: ui/page/wallets/restore_page.go [hunk 2]
```diff
@@ -438,12 +440,26 @@ func switchSeedEditors(editors []decredmaterial.RestoreEditor) {
 	}
 }
 
+func (pg *Restore) isSeedEditorChanged() bool {
```
Comment (Sirmorrison) [inline ui/page/wallets/restore_page.go]: Please add comment on what this does.

**Review by Sirmorrison — CHANGES_REQUESTED** [review]
Initially, using the tab key, the editor is populated however, this does not seem to work anymore.
image

File: ui/page/wallets/restore_page.go [hunk 3]
```diff
@@ -60,8 +60,10 @@ type Restore struct {
 	seedClicked  bool
 	isLastEditor bool
 
-	seedEditors seedEditors
-	keyEvent    chan *key.Event
+	seedEditors        seedEditors
+	keyEvent           chan *key.Event
+	seedEditorTracker  int
+	caretCoordXTracker float32
```
Comment (dreacot) [inline ui/page/wallets/restore_page.go]: what this variable does is unclear, please add a comment

**Comment by Sirmorrison** [comment]
This still does not populate the editor with the first suggestion when tab is pressed.

ezgif com-gif-maker(13)

**Comment by Sirmorrison** [comment]
image

image

When the highlight is on the last item, and the suggestion is reduced to 2, or less, the highlight is hidden. It should always be either on the last item or the first.

Also, when the focus shifts to the next editor, the highlight is also on the last item instead of the first as well.
This is also reproducible in master.

I believe we can have it resolved here as well.
ezgif com-gif-maker(14)

**Comment by dreacot** [comment]
1. `When the highlight is on the last item, and the suggestion is reduced to 2, or less, the highlight is hidden. It should always be either on the last item or the first.` this issue still occurs
2. `This still does not populate the editor with the first suggestion when tab is pressed.` this now populates the first suggestion, but when on the second suggestion, and tab is pressed the first suggestion is populated instead of the second

File: ui/page/wallets/restore_page.go [hunk 4]
```diff
@@ -365,15 +369,20 @@ func (pg *Restore) layoutSeedMenu(gtx layout.Context, optionsSeedMenuIndex int)
...
 	m := op.Record(gtx.Ops)
 	inset.Layout(gtx, func(gtx C) D {
-		border := widget.Border{Color: pg.Theme.Color.Gray4, CornerRadius: values.MarginPadding5, Width: values.MarginPadding2}
-		return border.Layout(gtx, func(gtx C) D {
-			return pg.optionsMenuCard.Layout(gtx, func(gtx C) D {
-				gtx.Constraints.Min.X = gtx.Constraints.Max.X
-				return (&layout.List{Axis: layout.Vertical}).Layout(gtx, len(pg.seedMenu), func(gtx C, i int) D {
-					return layout.UniformInset(values.MarginPadding0).Layout(gtx, pg.seedMenu[i].button.Layout)
+		if !pg.seedEditorChanged() && pg.caretCoordXChanged() {
+			fmt.Println(pg.selected)
```
Comment (dreacot) [inline ui/page/wallets/restore_page.go]: i believe this was used for debugging, if so, it can be removed

**Comment by dreacot** [comment]
"When the highlight is on the last item, and the suggestion is reduced to 2, or less, the highlight is hidden. It should always be either on the last item or the first". this issue still occurs

**Review by Sirmorrison — CHANGES_REQUESTED** [review]
PR functionality looks good so far. Just a little more update to be carried out.

When navigating to a previous editor, the suggestion should be based on the words already existing in the editor. This can be reproduced in master


image

**Comment by dreacot** [comment]
> "When the highlight is on the last item, and the suggestion is reduced to 2, or less, the highlight is hidden. It should always be either on the last item or the first". this issue still occurs

i'm still experiencing this

File: ui/page/wallets/restore_page.go [hunk 5]
```diff
@@ -62,6 +62,7 @@ type Restore struct {
 
 	seedEditors       seedEditors
 	keyEvent          chan *key.Event
+	onChangeCaretPos  int // caret position when seed editor is switched
 	caretPosition     int // current caret position
```
Comment (Sirmorrison) [inline ui/page/wallets/restore_page.go:66]: I believe these 2 have same function from the use case also, you have a method `caretPositionChanged()`. Why not leverage in this to carry out the change state. 

It leaves too many seemingly redundant types.

File: ui/page/wallets/restore_page.go [hunk 6]
```diff
@@ -401,20 +405,40 @@ func (pg *Restore) updateSeedResetBtn() bool {
 	return false
 }
 
-func (pg *Restore) validateSeeds() bool {
-	pg.seedPhrase = ""
+func (pg *Restore) validateSeeds() (bool, string) {
+	focus := pg.seedEditors.focusIndex
+	seedMatchCounter := 0
+	seedPhraseStore := ""
```
Comment (Sirmorrison) [inline ui/page/wallets/restore_page.go]: kindly comment this so we know what it does... not sure what `seedPhraseStore` is and can we use a better variable name?

File: ui/page/wallets/restore_page.go [hunk 7]
```diff
@@ -538,6 +573,46 @@ func (pg *Restore) HandleUserInteractions() {
...
+		pg.suggestions = nil
+		_, caretPos := pg.seedEditors.editors[pg.seedEditors.focusIndex].Edit.Editor.CaretPos()
+		pg.caretPosition = caretPos
+		pg.onChangeCaretPos = caretPos
+	}
+
+	if pg.caretPositionChanged() {
+		pg.selected = 0
+	}
+
```
Comment (Sirmorrison) [inline ui/page/wallets/restore_page.go]: Remove whitespace

File: ui/page/wallets/restore_page.go [hunk 8]
```diff
@@ -60,8 +60,11 @@ type Restore struct {
 	seedClicked  bool
 	isLastEditor bool
 
-	seedEditors seedEditors
-	keyEvent    chan *key.Event
+	seedEditors       seedEditors
+	keyEvent          chan *key.Event
+	onChangeCaretPos  int // caret position when seed editor is switched
+	caretPosition     int // current caret position
+	seedEditorTracker int // stores the current focus index of seed editors
```
Comment (Sirmorrison) [inline ui/page/wallets/restore_page.go]:
```suggestion
	nextCaretPosition  int // caret position when seed editor is switched
	currentCaretPosition     int // current caret position
	selectedSeedEditor int // stores the current focus index of seed editors
```

**Review by Sirmorrison — CHANGES_REQUESTED** [review]

**Review by Sirmorrison — APPROVED** [review]
