### PR TITLE
Fix "clear all fields" popup position while full screen in Send page

### LINKED ISSUE #576: "Clear all fields" position on Send page
On Send page, when the options button is clicked, "Clear all fields" appears but the position is not correct.
See image below:
Screenshot from 2021-08-21 19-01-13

### PR DESCRIPTION
**Pull request by JustinBeBoy**
Resolve #576 
This PR allows:

Fix a bug where the "clear all fields" popup position is not correct while full screen.

### CODE REVIEW

File: ui/page/send/layout.go [hunk 1]
```diff
@@ -66,7 +68,21 @@ func (pg *Page) topNav(gtx layout.Context) layout.Dimensions {
...
 					layout.Rigid(func(gtx C) D {
-						return layout.Inset{Left: m}.Layout(gtx, pg.moreOption.Layout)
+						return layout.Inset{Left: m}.Layout(gtx, func(gtx C) D {
+							return layout.Flex{Axis: layout.Vertical}.Layout(gtx,
+								layout.Rigid(func(gtx C) D {
+									if pg.moreOptionIsOpen {
+										macro := op.Record(gtx.Ops)
+										layout.Inset{Top: values.MarginPadding25, Left: unit.Dp(-90)}.Layout(gtx, func(gtx C) D {
+											return pg.clearAllBtn.Layout(gtx)
+										})
```
Comment (Sirmorrison) [inline ui/page/send/layout.go]:
```suggestion
										layout.Inset{Top: values.MarginPadding25, Left: unit.Dp(-90)}.Layout(gtx, pg.clearAllBtn.Layout)
```

File: ui/page/send/layout.go [hunk 2]
```diff
@@ -66,7 +68,21 @@ func (pg *Page) topNav(gtx layout.Context) layout.Dimensions {
 				return layout.Flex{Axis: layout.Horizontal}.Layout(gtx,
 					layout.Rigid(pg.infoButton.Layout),
 					layout.Rigid(func(gtx C) D {
-						return layout.Inset{Left: m}.Layout(gtx, pg.moreOption.Layout)
+						return layout.Inset{Left: m}.Layout(gtx, func(gtx C) D {
+							return layout.Flex{Axis: layout.Vertical}.Layout(gtx,
+								layout.Rigid(func(gtx C) D {
+									if pg.moreOptionIsOpen {
+										macro := op.Record(gtx.Ops)
+										layout.Inset{Top: values.MarginPadding25, Left: unit.Dp(-90)}.Layout(gtx, func(gtx C) D {
```
Comment (Sirmorrison) [inline ui/page/send/layout.go]: move `unit.Dp(-90)` to dimensions.go file.
it should look something like this `values.MarginPaddingMinus90`

File: ui/page/send/layout.go [hunk 3]
```diff
@@ -110,19 +126,6 @@ func (pg *Page) Layout(gtx layout.Context) layout.Dimensions {
...
 				}),
-				layout.Stacked(func(gtx C) D {
-					if pg.moreOptionIsOpen {
-						inset := layout.Inset{
-							Top:   values.MarginPadding40,
-							Right: values.MarginPadding20,
-						}
-						return inset.Layout(gtx, func(gtx C) D {
-							border := widget.Border{Color: pg.Theme.Color.Background, CornerRadius: values.MarginPadding5, Width: values.MarginPadding1}
-							return border.Layout(gtx, pg.clearAllBtn.Layout)
```
Comment (Sirmorrison) [inline ui/page/send/layout.go:121]: The border acts as a temporary shadow pending when the shadow widget/functionality is implemented.
With out this, this is what you have.
image

**Review by Sirmorrison — CHANGES_REQUESTED** [review]

**Review by Sirmorrison — APPROVED** [review]

**Review by beansgum — APPROVED** [review]
