### PR TITLE
Fix Key Event Bugs 

### LINKED ISSUE #714: Key event bugs
On send page, the behavior of the tab event is inconsistent. The following are observed:

- When focus is on Address editor and "To" is changed from Address to My account the focus is not on any editor. The focus should be on the Amount(DCR) editor 
- When "To" is set to My Account and Amount(DCR) is focused, the tab key switches forward but does not go back when pressed again (non-cyclic).

See video below:
https://streamable.com/cac3iu

Also, on the following pages, when the info button is clicked and dismissed tab event does not work anymore:

- Verify message page 
- Sign message page 
- Send page 

From my investigation, I noticed that this happens because the bool that is checked before enabling the key event listener only evaluates to true on page resume. However, when the info modal is open, the tab key still works if pressed as I could see it in the background. When "Got it" is clicked on, the tab key stops switching the editors.

See video below:
https://streamable.com/pun4ed

- Enter key does not dismiss info modal anymore

### PR DESCRIPTION
**Pull request by devchoplife**
Fixes #714 
This PR fixes the following bugs regarding key event:

- Ensure that tab key switches editors when info modal is open and dismissed on verify message page, sign message page and send page 
- Focus on dcr amount editor when "To" is changed to "My account" and also make the tab press cyclic 
- New event listener for info modal
- Enter key to close info modals

### CODE REVIEW

File: ui/load/load.go [hunk 1]
```diff
@@ -30,6 +30,7 @@ type Receiver struct {
 	InternalLog         chan string
 	NotificationsUpdate chan interface{}
 	KeyEvents           chan *key.Event
+	InfoModalEvents     chan *key.Event
```
Comment (Sirmorrison) [inline ui/load/load.go]: This is not needed

File: ui/modal/info_modal.go [hunk 2]
```diff
@@ -49,7 +49,7 @@ func NewInfoModal(l *load.Load) *InfoModal {
 		modal:        *l.Theme.ModalFloatTitle(),
 		btnPositve:   l.Theme.OutlineButton("Yes"),
 		btnNegative:  l.Theme.OutlineButton("No"),
-		keyEvent:     l.Receiver.KeyEvents,
+		keyEvent:     l.Receiver.InfoModalEvents,
```
Comment (Sirmorrison) [inline ui/modal/info_modal.go]: revert this. Use `KeyEvents`

File: ui/window.go [hunk 3]
```diff
@@ -56,6 +56,7 @@ type Window struct {
 	err string
 
 	keyEvents             chan *key.Event
+	infoModalEvents       chan *key.Event
```
Comment (Sirmorrison) [inline ui/window.go]: Remove.

File: ui/window.go [hunk 4]
```diff
@@ -99,6 +100,7 @@ func CreateWindow(wal *wallet.Wallet) (*Window, *app.Window, error) {
 	win.states.loading = false
 
 	win.keyEvents = make(chan *key.Event)
+	win.infoModalEvents = make(chan *key.Event)
```
Comment (Sirmorrison) [inline ui/window.go]: Remove

File: ui/window.go [hunk 5]
```diff
@@ -134,6 +136,7 @@ func (win *Window) NewLoad() (*load.Load, error) {
 
 	l.Receiver = &load.Receiver{
 		KeyEvents:           win.keyEvents,
+		InfoModalEvents:     win.infoModalEvents,
```
Comment (Sirmorrison) [inline ui/window.go]: Remove

File: ui/window.go [hunk 6]
```diff
@@ -369,6 +372,9 @@ func (win *Window) Loop(w *app.Window, shutdown chan int) {
 					if win.load.EnableKeyEvent {
 						win.keyEvents <- &evt
 					}
+					if win.load.EnableKeyEventOnInfoModal {
+						win.infoModalEvents <- &evt
```
Comment (Sirmorrison) [inline ui/window.go]:
```suggestion
						win.keyEvents <- &evt
```

File: ui/page/wallets/sign_message_page.go [hunk 7]
```diff
@@ -87,7 +87,6 @@ func (pg *SignMessagePage) ID() string {
 
 func (pg *SignMessagePage) OnResume() {
 	pg.addressEditor.Editor.Focus()
-	pg.Load.EnableKeyEvent = true
```
Comment (Sirmorrison) [inline ui/page/wallets/sign_message_page.go]: Kindly revert this.

File: ui/page/wallets/sign_message_page.go [hunk 8]
```diff
@@ -230,6 +229,7 @@ func (pg *SignMessagePage) updateButtonColors() {
 func (pg *SignMessagePage) Handle() {
 	gtx := pg.gtx
 	pg.updateButtonColors()
+	pg.Load.EnableKeyEvent = true
```
Comment (Sirmorrison) [inline ui/page/wallets/sign_message_page.go]: Any reason this was done?

File: ui/page/verify_message_page.go [hunk 9]
```diff
@@ -158,6 +157,7 @@ func (pg *VerifyMessagePage) verifyMessageResponse() layout.Widget {
 
 func (pg *VerifyMessagePage) Handle() {
 	pg.updateButtonColors()
+	pg.Load.EnableKeyEvent = true
```
Comment (Sirmorrison) [inline ui/page/verify_message_page.go]: Any specific reason for this?

File: ui/page/verify_message_page.go [hunk 10]
```diff
@@ -69,7 +69,6 @@ func (pg *VerifyMessagePage) ID() string {
 
 func (pg *VerifyMessagePage) OnResume() {
 	pg.addressEditor.Editor.Focus()
-	pg.Load.EnableKeyEvent = true
```
Comment (Sirmorrison) [inline ui/page/verify_message_page.go]: Please revert this.

**Review by Sirmorrison — CHANGES_REQUESTED** [review]
image

Switching to my account, sets the focus on the amount editor correctly. But switching back to address, sets the focus on the amount editor instead of the address editor since it is empty.

On the side, the color of the slider/switch is not correct. it is supposed to be `Gray1` not `Gray2` from the modal widget.

File: ui/page/wallets/sign_message_page.go (hunk 8 above)
Comment (devchoplife) [reply ui/page/wallets/sign_message_page.go:232]: Yeah,
I moved it here because when you open the info modal on a page with editors (the tab event is present here) and the modal is closed, tab key does not switch editors anymore because it was initialised OnResume

**Comment by Sirmorrison** [comment]
> image
> 
> Switching to my account, sets the focus on the amount editor correctly. But switching back to address, sets the focus on the amount editor instead of the address editor since it is empty.
> 
> On the side, the color of the slider/switch is not correct. it is supposed to be `Gray1` not `Gray2` from the modal widget.

I believe you may have missed out the first part of this comment with regards to editor focus.

Also, the comment was for the slider track background to be changed from `Gray1` to `Gray2`.

image

https://github.com/planetdecred/godcr/blob/4c5ba0a23f789cfad9c389295bbdfe6eb52e610f/ui/decredmaterial/switch.go#L177

File: ui/decredmaterial/switch.go [hunk 11]
```diff
@@ -51,7 +51,7 @@ func (t *Theme) SwitchButtonText(i []SwitchItem) *SwitchButtonText {
 		items: make([]SwitchItem, len(i)+1),
 	}
 
-	sw.active, sw.inactive = sw.t.Color.Surface, color.NRGBA{}
+	sw.active, sw.inactive = sw.t.Color.Gray3, color.NRGBA{}
```
Comment (Sirmorrison) [inline ui/decredmaterial/switch.go]: Revert this please.

**Review by Sirmorrison — CHANGES_REQUESTED** [review]

**Comment by devchoplife** [comment]
> > image
> > Switching to my account, sets the focus on the amount editor correctly. But switching back to address, sets the focus on the amount editor instead of the address editor since it is empty.
> > On the side, the color of the slider/switch is not correct. it is supposed to be `Gray1` not `Gray2` from the modal widget.
> 
> I believe you may have missed out the first part of this comment with regards to editor focus.
> 
> Also, the comment was for the slider track background to be changed from `Gray1` to `Gray2`.
> 
> image
> 
> https://github.com/planetdecred/godcr/blob/4c5ba0a23f789cfad9c389295bbdfe6eb52e610f/ui/decredmaterial/switch.go#L177

Changing the color here to Gray2 makes the text invisible 
Screenshot from 2021-12-21 23-18-21

Perhaps we have to change the text color too?

**Comment by Sirmorrison** [comment]
> > > image
> > > Switching to my account, sets the focus on the amount editor correctly. But switching back to address, sets the focus on the amount editor instead of the address editor since it is empty.
> > > On the side, the color of the slider/switch is not correct. it is supposed to be `Gray1` not `Gray2` from the modal widget.
> > 
> > 
> > I believe you may have missed out the first part of this comment with regards to editor focus.
> > Also, the comment was for the slider track background to be changed from `Gray1` to `Gray2`.
> > image
> > https://github.com/planetdecred/godcr/blob/4c5ba0a23f789cfad9c389295bbdfe6eb52e610f/ui/decredmaterial/switch.go#L177
> 
> Changing the color here to Gray2 makes the text invisible Screenshot from 2021-12-21 23-18-21
> 
> Perhaps we have to change the text color too?

The card color should be `Gray 2` and the text color should be `GrayText1` for inactive text color and `Text` for active text color.

**Review by Sirmorrison — APPROVED** [review]
