### PR TITLE
Verify bug fix

### LINKED ISSUE #552: verify message page bug.
On the verify message page the below errors are noticed.
ezgif com-gif-maker(6)

* when page first loads, the clear all button is hidden and the verify message button is active.
* The `Clear all` button is grayed out even when one or more input fields are not empty. The expected behavior is for the `Clear all` button to be active when one or more input fields are not empty from the mockup.

image

image

* the `Invalid signature or message` error message is wrongly placed. from the mockup, it is supposed to be at the bottom of the page. 
image

* Error messages does not clear after the correct value has been entered.
image

### PR DESCRIPTION
**Pull request by Sirmorrison**
close #552 
- Fix validation, button color updates and error message display.
- Fix validation button color updates on validate address page.

### CODE REVIEW

File: ui/page/verify_message_page.go [hunk 1]
```diff
@@ -143,23 +158,27 @@ func (pg *VerifyMessagePage) verifyMessageResponse() layout.Widget {
...
 			}
-			pg.signInput.SetError("")
+		}
+	}
 
-			if !valid {
-				pg.verifyMessageStatus = pg.Icons.NavigationCancel
+	if pg.verifyButton.Button.Clicked() || handleSubmitEvent(pg.addressEditor.Editor, pg.messageEditor.Editor, pg.signatureEditor.Editor) {
+		if pg.validateAllInputs() {
+			fmt.Println("im here")
```
Comment (oshorefueled) [inline ui/page/verify_message_page.go]: kindly remove this.

File: ui/page/verify_message_page.go [hunk 2]
```diff
@@ -170,56 +189,63 @@ func (pg *VerifyMessagePage) Handle() {
...
+}
 
-func (pg *VerifyMessagePage) handlerEditorEvents(w *widget.Editor) {
-	for _, evt := range w.Events() {
-		switch evt.(type) {
-		case widget.ChangeEvent:
-			pg.validateAddress()
-			return
-		}
+func (pg *VerifyMessagePage) updateColors() {
```
Comment (oshorefueled) [inline ui/page/verify_message_page.go]: updateButtonColors would be a less vague method name.

File: ui/page/sign_message_page.go [hunk 3]
```diff
@@ -206,9 +205,12 @@ func (pg *SignMessagePage) drawResult() layout.Widget {
 }
 
 func (pg *SignMessagePage) updateColors() {
```
Comment (oshorefueled) [inline ui/page/sign_message_page.go]: This would be less vague as updateButtonColors

**Review by oshorefueled — DISMISSED** [review]

**Review by beansgum — APPROVED** [review]

**Review by dreacot — APPROVED** [review]
